const std = @import("std");
const types = @import("types.zig");

const PluginInfo = types.PluginInfo;
const DiscoveredCommands = types.DiscoveredCommands;
const CommandInfo = types.CommandInfo;
const CommandType = types.CommandType;
const BuildConfig = types.BuildConfig;

// ============================================================================
// SIMPLE CODE GENERATION - Minimal registry source generation with comptime
// ============================================================================

/// Generate comptime registry source code
pub fn generateComptimeRegistrySource(
    allocator: std.mem.Allocator,
    commands: DiscoveredCommands,
    config: BuildConfig,
    plugins: []const PluginInfo,
) ![]u8 {
    var aw: std.Io.Writer.Allocating = .init(allocator);
    defer aw.deinit();
    const writer = &aw.writer;

    // Generate header
    try writer.writeAll("// Generated by zcli - DO NOT EDIT\n\n");
    try writer.writeAll("const std = @import(\"std\");\n");
    try writer.writeAll("const zcli = @import(\"zcli\");\n\n");

    // Generate command imports
    try generateCommandImports(writer, commands);

    // Generate plugin imports
    try generatePluginImports(writer, plugins, allocator);

    // Generate the simple registry
    try generateSimpleRegistry(writer, commands, config, plugins, allocator);

    // Generate pure command groups metadata
    try generatePureCommandGroups(writer, commands, allocator);

    var al = aw.toArrayList();
    return al.toOwnedSlice(allocator);
}

/// Generate command module imports
fn generateCommandImports(writer: anytype, commands: DiscoveredCommands) !void {
    var it = commands.root.iterator();
    while (it.next()) |entry| {
        const cmd_name = entry.key_ptr.*;
        const cmd_info = entry.value_ptr.*;

        if (cmd_info.command_type != .leaf) {
            // Generate import for optional group with index file
            if (cmd_info.command_type == .optional_group) {
                const module_name = try std.fmt.allocPrint(commands.allocator, "{s}_index", .{cmd_name});
                defer commands.allocator.free(module_name);

                try writer.print("const {s} = @import(\"{s}\");\n", .{ module_name, module_name });
            }
            // Generate imports for subcommands
            try generateGroupImports(writer, cmd_name, &cmd_info);
        } else {
            const module_name = if (std.mem.eql(u8, cmd_name, "test"))
                "cmd_test"
            else
                try std.fmt.allocPrint(commands.allocator, "cmd_{s}", .{cmd_name});
            defer if (!std.mem.eql(u8, cmd_name, "test")) commands.allocator.free(module_name);

            try writer.print("const {s} = @import(\"{s}\");\n", .{ module_name, module_name });
        }
    }
    try writer.writeAll("\n");
}

/// Generate group command imports recursively
fn generateGroupImports(writer: anytype, _: []const u8, group_info: *const CommandInfo) !void {
    if (group_info.subcommands) |subcommands| {
        var it = subcommands.iterator();
        while (it.next()) |entry| {
            const subcmd_name = entry.key_ptr.*;
            const subcmd_info = entry.value_ptr.*;

            if (subcmd_info.command_type == .optional_group) {
                // Generate import for optional group with index file
                var module_name_parts = std.ArrayList([]const u8).empty;
                defer module_name_parts.deinit(subcommands.allocator);

                for (subcmd_info.path) |part| {
                    const sanitized_part = try sanitizeIdentifier(subcommands.allocator, part);
                    defer subcommands.allocator.free(sanitized_part);
                    try module_name_parts.append(subcommands.allocator, try subcommands.allocator.dupe(u8, sanitized_part));
                }

                const module_name = try std.mem.join(subcommands.allocator, "_", module_name_parts.items);
                defer {
                    for (module_name_parts.items) |part| {
                        subcommands.allocator.free(part);
                    }
                    subcommands.allocator.free(module_name);
                }

                const module_name_with_index = try std.fmt.allocPrint(subcommands.allocator, "{s}_index", .{module_name});
                defer subcommands.allocator.free(module_name_with_index);

                try writer.print("const {s} = @import(\"{s}\");\n", .{ module_name_with_index, module_name_with_index });

                // Also recurse for subcommands
                try generateGroupImports(writer, subcmd_name, &subcmd_info);
            } else if (subcmd_info.command_type == .pure_group) {
                // Pure groups have no imports, just recurse
                try generateGroupImports(writer, subcmd_name, &subcmd_info);
            } else {
                // Generate module name from full command path to match module_creation.zig
                var module_name_parts = std.ArrayList([]const u8).empty;
                defer module_name_parts.deinit(subcommands.allocator);

                for (subcmd_info.path) |part| {
                    const sanitized_part = try sanitizeIdentifier(subcommands.allocator, part);
                    defer subcommands.allocator.free(sanitized_part);
                    try module_name_parts.append(subcommands.allocator, try subcommands.allocator.dupe(u8, sanitized_part));
                }

                const module_name = try std.mem.join(subcommands.allocator, "_", module_name_parts.items);
                defer {
                    for (module_name_parts.items) |part| {
                        subcommands.allocator.free(part);
                    }
                    subcommands.allocator.free(module_name);
                }

                try writer.print("const {s} = @import(\"{s}\");\n", .{ module_name, module_name });
            }
        }
    }
}

/// Generate plugin imports and initialization
fn generatePluginImports(writer: anytype, plugins: []const PluginInfo, allocator: std.mem.Allocator) !void {
    for (plugins) |plugin_info| {
        const plugin_var_name = try pluginVarName(allocator, plugin_info.name);
        defer allocator.free(plugin_var_name);

        if (plugin_info.init) |init_code| {
            // Plugin has initialization code - call it on import
            try writer.print("const {s} = @import(\"{s}\"){s};\n", .{ plugin_var_name, plugin_info.import_name, init_code });
        } else {
            // Normal plugin without config - import directly
            try writer.print("const {s} = @import(\"{s}\");\n", .{ plugin_var_name, plugin_info.import_name });
        }
    }
    if (plugins.len > 0) {
        try writer.writeAll("\n");
    }
}

/// Render `s` escaped for the inside of a double-quoted Zig string literal.
/// App metadata comes from build.zig and command paths from the filesystem —
/// a quote, backslash, or newline in them must not break out of (or inject
/// code after) the generated literal.
fn escapeStringLiteral(allocator: std.mem.Allocator, s: []const u8) ![]u8 {
    var aw: std.Io.Writer.Allocating = .init(allocator);
    defer aw.deinit();
    try std.zig.stringEscape(s, &aw.writer);
    var al = aw.toArrayList();
    return al.toOwnedSlice(allocator);
}

/// Generate the simple comptime registry
fn generateSimpleRegistry(writer: anytype, commands: DiscoveredCommands, config: BuildConfig, plugins: []const PluginInfo, allocator: std.mem.Allocator) !void {
    const app_name = try escapeStringLiteral(allocator, config.app_name);
    defer allocator.free(app_name);
    const app_version = try escapeStringLiteral(allocator, config.app_version);
    defer allocator.free(app_version);
    const app_description = try escapeStringLiteral(allocator, config.app_description);
    defer allocator.free(app_description);

    // Generate the registry type (private)
    try writer.print(
        \\const RegistryType = zcli.Registry.init(.{{
        \\    .app_name = "{s}",
        \\    .app_version = "{s}",
        \\    .app_description = "{s}",
        \\}})
    , .{ app_name, app_version, app_description });

    // Register commands
    try generateCommandRegistrations(writer, commands, allocator);

    // Register plugins
    try generatePluginRegistrations(writer, plugins, allocator);

    // Build the final registry type
    try writer.writeAll("\n    .build();\n\n");

    // Export app config constants and initialization function
    try writer.print(
        \\pub const Context = RegistryType.Context;
        \\pub const command_info = RegistryType.command_info;
        \\pub const global_options_info = RegistryType.global_options_info;
        \\pub const app_name = "{s}";
        \\pub const app_version = "{s}";
        \\pub const app_description = "{s}";
        \\
        \\pub fn init() RegistryType {{
        \\    return RegistryType.init();
        \\}}
        \\
    , .{ app_name, app_version, app_description });
}

/// Generate metadata for pure command groups
fn generatePureCommandGroups(writer: anytype, commands: DiscoveredCommands, allocator: std.mem.Allocator) !void {
    try writer.writeAll("// Pure command groups (directories without index.zig)\n");
    try writer.writeAll("pub const pure_command_groups = [_][]const []const u8{\n");

    // Recursively find and generate pure command groups
    try generatePureGroupsFromMap(writer, &commands.root, allocator);

    try writer.writeAll("};\n\n");
}

/// Recursively generate pure command group entries
fn generatePureGroupsFromMap(writer: anytype, command_map: *const std.StringHashMap(CommandInfo), allocator: std.mem.Allocator) !void {
    var it = command_map.iterator();
    while (it.next()) |entry| {
        const cmd_info = entry.value_ptr.*;

        if (cmd_info.command_type == .pure_group) {
            // Generate entry for this pure group
            try writer.writeAll("    &.{");
            for (cmd_info.path, 0..) |component, idx| {
                if (idx > 0) try writer.writeAll(", ");
                const component_lit = try escapeStringLiteral(allocator, component);
                defer allocator.free(component_lit);
                try writer.print("\"{s}\"", .{component_lit});
            }
            try writer.writeAll("},\n");
        }

        // Recursively process subcommands
        if (cmd_info.subcommands) |subcommands| {
            try generatePureGroupsFromMap(writer, &subcommands, allocator);
        }
    }
}

/// Generate command registrations
fn generateCommandRegistrations(writer: anytype, commands: DiscoveredCommands, allocator: std.mem.Allocator) !void {
    var it = commands.root.iterator();
    while (it.next()) |entry| {
        const cmd_name = entry.key_ptr.*;
        const cmd_info = entry.value_ptr.*;

        if (cmd_info.command_type != .leaf) {
            // Register optional group with index file as a command
            if (cmd_info.command_type == .optional_group) {
                const module_name = try std.fmt.allocPrint(allocator, "{s}_index", .{cmd_name});
                defer allocator.free(module_name);

                const command_path_str = try std.mem.join(allocator, " ", cmd_info.path);
                defer allocator.free(command_path_str);
                const command_path_lit = try escapeStringLiteral(allocator, command_path_str);
                defer allocator.free(command_path_lit);

                try writer.print("\n    .register(\"{s}\", {s})", .{ command_path_lit, module_name });
            }
            // Register subcommands
            try generateGroupRegistrations(writer, cmd_name, &cmd_info, allocator);
        } else {
            const module_name = if (std.mem.eql(u8, cmd_name, "test"))
                "cmd_test"
            else
                try std.fmt.allocPrint(allocator, "cmd_{s}", .{cmd_name});
            defer if (!std.mem.eql(u8, cmd_name, "test")) allocator.free(module_name);

            // Use the actual command path from CommandInfo (it's now an array)
            const command_path_str = try std.mem.join(allocator, " ", cmd_info.path);
            defer allocator.free(command_path_str);
            const command_path_lit = try escapeStringLiteral(allocator, command_path_str);
            defer allocator.free(command_path_lit);

            try writer.print("\n    .register(\"{s}\", {s})", .{ command_path_lit, module_name });
        }
    }
}

/// Generate group command registrations recursively
fn generateGroupRegistrations(writer: anytype, _: []const u8, group_info: *const CommandInfo, allocator: std.mem.Allocator) !void {
    if (group_info.subcommands) |subcommands| {
        var it = subcommands.iterator();
        while (it.next()) |entry| {
            const subcmd_name = entry.key_ptr.*;
            const subcmd_info = entry.value_ptr.*;

            if (subcmd_info.command_type == .optional_group) {
                // Register the optional group itself
                var module_name_parts = std.ArrayList([]const u8).empty;
                defer module_name_parts.deinit(allocator);

                for (subcmd_info.path) |part| {
                    const sanitized_part = try sanitizeIdentifier(allocator, part);
                    defer allocator.free(sanitized_part);
                    try module_name_parts.append(allocator, try allocator.dupe(u8, sanitized_part));
                }

                const module_name = try std.mem.join(allocator, "_", module_name_parts.items);
                defer {
                    for (module_name_parts.items) |part| {
                        allocator.free(part);
                    }
                    allocator.free(module_name);
                }

                const module_name_with_index = try std.fmt.allocPrint(allocator, "{s}_index", .{module_name});
                defer allocator.free(module_name_with_index);

                const command_path_str = try std.mem.join(allocator, " ", subcmd_info.path);
                defer allocator.free(command_path_str);
                const command_path_lit = try escapeStringLiteral(allocator, command_path_str);
                defer allocator.free(command_path_lit);

                try writer.print("\n    .register(\"{s}\", {s})", .{ command_path_lit, module_name_with_index });

                // Also recurse for its subcommands
                try generateGroupRegistrations(writer, subcmd_name, &subcmd_info, allocator);
            } else if (subcmd_info.command_type == .pure_group) {
                // Pure groups are not registered, just recurse
                try generateGroupRegistrations(writer, subcmd_name, &subcmd_info, allocator);
            } else {
                // Generate module name from full command path to match module_creation.zig
                var module_name_parts = std.ArrayList([]const u8).empty;
                defer module_name_parts.deinit(allocator);

                for (subcmd_info.path) |part| {
                    const sanitized_part = try sanitizeIdentifier(allocator, part);
                    defer allocator.free(sanitized_part);
                    try module_name_parts.append(allocator, try allocator.dupe(u8, sanitized_part));
                }

                const module_name = try std.mem.join(allocator, "_", module_name_parts.items);
                defer {
                    for (module_name_parts.items) |part| {
                        allocator.free(part);
                    }
                    allocator.free(module_name);
                }

                // Use the actual command path from the CommandInfo (it's now an array)
                const command_path_str = try std.mem.join(allocator, " ", subcmd_info.path);
                defer allocator.free(command_path_str);
                const command_path_lit = try escapeStringLiteral(allocator, command_path_str);
                defer allocator.free(command_path_lit);

                try writer.print("\n    .register(\"{s}\", {s})", .{ command_path_lit, module_name });
            }
        }
    }
}

/// Generate plugin registrations
fn generatePluginRegistrations(writer: anytype, plugins: []const PluginInfo, allocator: std.mem.Allocator) !void {
    for (plugins) |plugin_info| {
        const plugin_var_name = try pluginVarName(allocator, plugin_info.name);
        defer allocator.free(plugin_var_name);

        try writer.print("\n    .registerPlugin({s})", .{plugin_var_name});
    }
}

/// Convert plugin name to valid Zig variable name (replace hyphens with
/// underscores). Always returns an allocation the caller owns — the previous
/// `catch plugin_name` swallowed OOM and emitted the unsanitized name.
fn pluginVarName(allocator: std.mem.Allocator, plugin_name: []const u8) ![]u8 {
    return std.mem.replaceOwned(u8, allocator, plugin_name, "-", "_");
}

/// Sanitize command name to valid Zig identifier (replace hyphens with
/// underscores). Always returns an allocation the caller owns.
fn sanitizeIdentifier(allocator: std.mem.Allocator, name: []const u8) ![]u8 {
    return std.mem.replaceOwned(u8, allocator, name, "-", "_");
}

// ============================================================================
// Tests
// ============================================================================

// Test helper for creating plugin structures
// Test helper for creating plugin structures
const PluginTestHelper = struct {
    allocator: std.mem.Allocator,
    plugins: std.ArrayList(PluginInfo),

    fn init(allocator: std.mem.Allocator) PluginTestHelper {
        return .{
            .allocator = allocator,
            .plugins = std.ArrayList(PluginInfo).empty,
        };
    }

    fn deinit(self: *PluginTestHelper) void {
        for (self.plugins.items) |plugin_info| {
            self.allocator.free(plugin_info.name);
            self.allocator.free(plugin_info.import_name);
        }
        self.plugins.deinit(self.allocator);
    }

    fn addLocal(self: *PluginTestHelper, name: []const u8, import_name: []const u8) !void {
        try self.plugins.append(self.allocator, .{
            .name = try self.allocator.dupe(u8, name),
            .import_name = try self.allocator.dupe(u8, import_name),
            .is_local = true,
            .dependency = null,
        });
    }

    fn addExternal(self: *PluginTestHelper, name: []const u8) !void {
        try self.plugins.append(self.allocator, .{
            .name = try self.allocator.dupe(u8, name),
            .import_name = try self.allocator.dupe(u8, name),
            .is_local = false,
            .dependency = null, // In real scenario, this would be from b.lazyDependency
        });
    }
};

test "app metadata is escaped into valid string literals" {
    const allocator = std.testing.allocator;

    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(CommandInfo).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = &.{},
        .app_name = "my-app",
        .app_version = "1.0.0",
        .app_description = "say \"hi\"\nback\\slash",
    };

    const source = try generateComptimeRegistrySource(allocator, commands, config, &.{});
    defer allocator.free(source);

    // Quote, newline, and backslash must all be escaped inside the literal —
    // an unescaped one terminates the string and injects the rest as code.
    try std.testing.expect(std.mem.indexOf(u8, source, ".app_description = \"say \\\"hi\\\"\\nback\\\\slash\",") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "\"say \"hi\"") == null);
}

test "plugin registry generation with imports" {
    const allocator = std.testing.allocator;
    var test_plugins = PluginTestHelper.init(allocator);
    defer test_plugins.deinit();

    try test_plugins.addLocal("logger", "plugins/logger");
    try test_plugins.addExternal("zcli-auth");

    // Create mock discovered commands
    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(CommandInfo).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = test_plugins.plugins.items,
        .app_name = "test-app",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    // Generate registry source
    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        test_plugins.plugins.items,
    );
    defer allocator.free(source);

    // Verify generated content includes plugin imports
    try std.testing.expect(std.mem.indexOf(u8, source, "const logger = @import(\"plugins/logger\");") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const zcli_auth = @import(\"zcli-auth\");") != null);

    // Verify new comptime registry Context generation
    try std.testing.expect(std.mem.indexOf(u8, source, "pub const Context = RegistryType.Context;") != null);

    // Verify registry generation (replaces pipeline generation)
    try std.testing.expect(std.mem.indexOf(u8, source, "const RegistryType = zcli.Registry.init") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".build();") != null);
    // Note: In the new comptime approach, plugins are registered and called through the registry
    // rather than generating complex pipeline code
}

test "plugin name sanitization for imports" {
    const allocator = std.testing.allocator;
    var test_plugins = PluginTestHelper.init(allocator);
    defer test_plugins.deinit();

    // Add plugin with dash in name (should be converted to underscore)
    try test_plugins.addExternal("zcli-help");
    try test_plugins.addExternal("my-custom-plugin");

    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(CommandInfo).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = test_plugins.plugins.items,
        .app_name = "test-app",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        test_plugins.plugins.items,
    );
    defer allocator.free(source);

    // Verify dashes are converted to underscores in variable names
    try std.testing.expect(std.mem.indexOf(u8, source, "const zcli_help = @import(\"zcli-help\");") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const my_custom_plugin = @import(\"my-custom-plugin\");") != null);
}

test "Context extension generation" {
    const allocator = std.testing.allocator;
    var test_plugins = PluginTestHelper.init(allocator);
    defer test_plugins.deinit();

    try test_plugins.addLocal("auth", "plugins/auth");
    try test_plugins.addLocal("logger", "plugins/logger");

    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(CommandInfo).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = test_plugins.plugins.items,
        .app_name = "test-app",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        test_plugins.plugins.items,
    );
    defer allocator.free(source);

    // Verify plugins are registered with the registry
    try std.testing.expect(std.mem.indexOf(u8, source, ".registerPlugin(auth)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".registerPlugin(logger)") != null);

    // Verify new init function signature
    try std.testing.expect(std.mem.indexOf(u8, source, "pub fn init() RegistryType") != null);

    // Note: The new registry approach doesn't need a deinit function
}

test "pipeline composition ordering" {
    const allocator = std.testing.allocator;
    var test_plugins = PluginTestHelper.init(allocator);
    defer test_plugins.deinit();

    // Order matters - last plugin wraps first
    try test_plugins.addLocal("plugin1", "plugins/plugin1");
    try test_plugins.addLocal("plugin2", "plugins/plugin2");
    try test_plugins.addLocal("plugin3", "plugins/plugin3");

    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(CommandInfo).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = test_plugins.plugins.items,
        .app_name = "test-app",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        test_plugins.plugins.items,
    );
    defer allocator.free(source);

    // In the new approach, verify plugins are registered in the correct order
    const plugin1_pos = std.mem.indexOf(u8, source, ".registerPlugin(plugin1)").?;
    const plugin2_pos = std.mem.indexOf(u8, source, ".registerPlugin(plugin2)").?;
    const plugin3_pos = std.mem.indexOf(u8, source, ".registerPlugin(plugin3)").?;

    // They should appear in the order they were added
    try std.testing.expect(plugin1_pos < plugin2_pos);
    try std.testing.expect(plugin2_pos < plugin3_pos);
}

test "Commands struct with plugin commands" {
    const allocator = std.testing.allocator;
    var test_plugins = PluginTestHelper.init(allocator);
    defer test_plugins.deinit();

    try test_plugins.addLocal("auth", "plugins/auth");
    try test_plugins.addExternal("zcli-help");

    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(CommandInfo).init(allocator),
    };
    defer commands.deinit();

    // Add a native command
    var hello_path = try allocator.alloc([]const u8, 1);
    hello_path[0] = try allocator.dupe(u8, "hello");

    const hello_cmd = CommandInfo{
        .name = try allocator.dupe(u8, "hello"),
        .path = hello_path,
        .file_path = try allocator.dupe(u8, "src/commands/hello.zig"),
        .command_type = .leaf,
        .subcommands = null,
    };
    try commands.root.put(try allocator.dupe(u8, "hello"), hello_cmd);

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = test_plugins.plugins.items,
        .app_name = "test-app",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        test_plugins.plugins.items,
    );
    defer allocator.free(source);

    // Verify commands are registered with the registry (new approach)
    try std.testing.expect(std.mem.indexOf(u8, source, "const cmd_hello = @import(\"cmd_hello\");") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".register(\"hello\", cmd_hello)") != null);

    // Verify plugins are also registered (combined approach)
    try std.testing.expect(std.mem.indexOf(u8, source, ".registerPlugin(auth)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".registerPlugin(zcli_help)") != null);

    // Verify registry is built
    try std.testing.expect(std.mem.indexOf(u8, source, ".build();") != null);

    // Note: The new registry approach handles command discovery differently
}

test "empty plugin list handling" {
    const allocator = std.testing.allocator;

    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(CommandInfo).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = null, // No plugins
        .app_name = "test-app",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        &.{}, // Empty plugin array
    );
    defer allocator.free(source);

    // Should still generate valid code with no plugins
    try std.testing.expect(std.mem.indexOf(u8, source, "pub const Context = RegistryType.Context;") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const RegistryType = zcli.Registry.init") != null);

    // Registry should build successfully even with no plugins
    try std.testing.expect(std.mem.indexOf(u8, source, ".build();") != null);
}

test "generated code structure validation" {
    const allocator = std.testing.allocator;

    // Create test plugin info
    var plugins = std.ArrayList(PluginInfo).empty;
    defer plugins.deinit(allocator);

    try plugins.append(allocator, .{
        .name = try allocator.dupe(u8, "test-plugin"),
        .import_name = try allocator.dupe(u8, "plugins/test"),
        .is_local = true,
        .dependency = null,
    });
    defer allocator.free(plugins.items[0].name);
    defer allocator.free(plugins.items[0].import_name);

    // Create empty commands for simplicity
    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(CommandInfo).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = "src/plugins",
        .plugins = plugins.items,
        .app_name = "testapp",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    // Generate registry source
    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        plugins.items,
    );
    defer allocator.free(source);

    // Validate key structures are present in new registry format
    try std.testing.expect(std.mem.indexOf(u8, source, "pub const Context = RegistryType.Context;") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const RegistryType = zcli.Registry.init") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".build();") != null);

    // Verify plugins are registered
    try std.testing.expect(std.mem.indexOf(u8, source, ".registerPlugin(") != null);

    // Validate plugin is referenced
    try std.testing.expect(std.mem.indexOf(u8, source, "test_plugin") != null);
}
