const std = @import("std");
const types = @import("types.zig");
const identifier = @import("../identifier.zig");
const module_names = @import("module_names.zig");

const PluginInfo = types.PluginInfo;
const DiscoveredCommands = types.DiscoveredCommands;
const DiscoveredCommand = types.DiscoveredCommand;
const CommandType = types.CommandType;
const BuildConfig = types.BuildConfig;

// ============================================================================
// SIMPLE CODE GENERATION - Minimal registry source generation with comptime
// ============================================================================

/// Generate comptime registry source code
pub fn generateComptimeRegistrySource(
    allocator: std.mem.Allocator,
    commands: DiscoveredCommands,
    config: BuildConfig,
    plugins: []const PluginInfo,
) ![]u8 {
    var aw: std.Io.Writer.Allocating = .init(allocator);
    defer aw.deinit();
    const writer = &aw.writer;

    // Generate header
    try writer.writeAll("// Generated by zcli - DO NOT EDIT\n\n");
    try writer.writeAll("const std = @import(\"std\");\n");
    try writer.writeAll("const zcli = @import(\"zcli\");\n\n");

    // Generate command imports
    try generateCommandImports(writer, commands);

    // Generate plugin imports
    try generatePluginImports(writer, plugins, allocator);

    // Generate the simple registry
    try generateSimpleRegistry(writer, commands, config, plugins, allocator);

    // Generate pure command groups metadata
    try generatePureCommandGroups(writer, commands, allocator);

    var al = aw.toArrayList();
    return al.toOwnedSlice(allocator);
}

/// Generate command module imports
fn generateCommandImports(writer: anytype, commands: DiscoveredCommands) !void {
    // One walk of the tree (module_names.flatten), shared with the registration
    // pass below and with module_creation.zig, so import strings can never drift
    // from registered module names. Ordering is pre-order + alphabetical, so the
    // generated registry is deterministic rather than filesystem-iteration ordered.
    const emitted = try module_names.flatten(commands.allocator, commands);
    defer module_names.freeEmitted(commands.allocator, emitted);
    for (emitted) |e| {
        try writer.print("const {s} = @import(\"{s}\");\n", .{ e.module_name, e.module_name });
    }
    try writer.writeAll("\n");
}

/// Generate plugin imports and initialization
fn generatePluginImports(writer: anytype, plugins: []const PluginInfo, allocator: std.mem.Allocator) !void {
    for (plugins) |plugin_info| {
        const plugin_var_name = try pluginVarName(allocator, plugin_info.name);
        defer allocator.free(plugin_var_name);

        // Escape the import path into the string literal — belt-and-braces with
        // the up-front name validation in main.zig, and the right thing for
        // built-in `.path` imports too.
        const import_lit = try escapeStringLiteral(allocator, plugin_info.import_name);
        defer allocator.free(import_lit);

        if (plugin_info.config) |config_literal| {
            // Plugin has config — apply it via the plugin's comptime init().
            // The literal gets its result type from init's Config parameter.
            try writer.print("const {s} = @import(\"{s}\").init({s});\n", .{ plugin_var_name, import_lit, config_literal });
        } else {
            // Normal plugin without config - import directly
            try writer.print("const {s} = @import(\"{s}\");\n", .{ plugin_var_name, import_lit });
        }
    }
    if (plugins.len > 0) {
        try writer.writeAll("\n");
    }
}

/// Render `s` escaped for the inside of a double-quoted Zig string literal.
/// App metadata comes from build.zig and command paths from the filesystem —
/// a quote, backslash, or newline in them must not break out of (or inject
/// code after) the generated literal.
fn escapeStringLiteral(allocator: std.mem.Allocator, s: []const u8) ![]u8 {
    var aw: std.Io.Writer.Allocating = .init(allocator);
    defer aw.deinit();
    try std.zig.stringEscape(s, &aw.writer);
    var al = aw.toArrayList();
    return al.toOwnedSlice(allocator);
}

/// Generate the simple comptime registry
fn generateSimpleRegistry(writer: anytype, commands: DiscoveredCommands, config: BuildConfig, plugins: []const PluginInfo, allocator: std.mem.Allocator) !void {
    const app_name = try escapeStringLiteral(allocator, config.app_name);
    defer allocator.free(app_name);
    const app_version = try escapeStringLiteral(allocator, config.app_version);
    defer allocator.free(app_version);
    const app_description = try escapeStringLiteral(allocator, config.app_description);
    defer allocator.free(app_description);

    // Generate the registry type (private)
    try writer.print(
        \\const RegistryType = zcli.Registry.init(.{{
        \\    .app_name = "{s}",
        \\    .app_version = "{s}",
        \\    .app_description = "{s}",
        \\}})
    , .{ app_name, app_version, app_description });

    // Register commands
    try generateCommandRegistrations(writer, commands, allocator);

    // Register plugins
    try generatePluginRegistrations(writer, plugins, allocator);

    // Build the final registry type
    try writer.writeAll("\n    .build();\n\n");

    // Export app config constants and initialization function
    try writer.print(
        \\pub const Context = RegistryType.Context;
        \\pub const command_info = RegistryType.command_info;
        \\pub const global_options_info = RegistryType.global_options_info;
        \\pub const app_name = "{s}";
        \\pub const app_version = "{s}";
        \\pub const app_description = "{s}";
        \\
        \\pub fn init() RegistryType {{
        \\    return RegistryType.init();
        \\}}
        \\
    , .{ app_name, app_version, app_description });
}

/// Generate metadata for pure command groups
fn generatePureCommandGroups(writer: anytype, commands: DiscoveredCommands, allocator: std.mem.Allocator) !void {
    try writer.writeAll("// Pure command groups (directories without index.zig)\n");
    try writer.writeAll("pub const pure_command_groups = [_][]const []const u8{\n");

    // Recursively find and generate pure command groups
    try generatePureGroupsFromMap(writer, &commands.root, allocator);

    try writer.writeAll("};\n\n");
}

/// Recursively generate pure command group entries
fn generatePureGroupsFromMap(writer: anytype, command_map: *const std.StringHashMap(DiscoveredCommand), allocator: std.mem.Allocator) !void {
    const sorted = try types.sortedByName(allocator, command_map);
    defer allocator.free(sorted);
    for (sorted) |cmd_info| {
        if (cmd_info.command_type == .pure_group) {
            // Generate entry for this pure group
            try writer.writeAll("    &.{");
            for (cmd_info.path, 0..) |component, idx| {
                if (idx > 0) try writer.writeAll(", ");
                const component_lit = try escapeStringLiteral(allocator, component);
                defer allocator.free(component_lit);
                try writer.print("\"{s}\"", .{component_lit});
            }
            try writer.writeAll("},\n");
        }

        // Recursively process subcommands
        if (cmd_info.subcommands) |subcommands| {
            try generatePureGroupsFromMap(writer, &subcommands, allocator);
        }
    }
}

/// Generate command registrations
fn generateCommandRegistrations(writer: anytype, commands: DiscoveredCommands, allocator: std.mem.Allocator) !void {
    // Same single walk as the import pass: registration order becomes the
    // registry's command order (and thus the order help/completions read back),
    // which flatten already emits alphabetically and pre-order.
    const emitted = try module_names.flatten(allocator, commands);
    defer module_names.freeEmitted(allocator, emitted);
    for (emitted) |e| {
        const command_path_str = try std.mem.join(allocator, " ", e.path);
        defer allocator.free(command_path_str);
        const command_path_lit = try escapeStringLiteral(allocator, command_path_str);
        defer allocator.free(command_path_lit);

        try writer.print("\n    .register(\"{s}\", {s})", .{ command_path_lit, e.module_name });
    }
}

/// Generate plugin registrations
fn generatePluginRegistrations(writer: anytype, plugins: []const PluginInfo, allocator: std.mem.Allocator) !void {
    for (plugins) |plugin_info| {
        const plugin_var_name = try pluginVarName(allocator, plugin_info.name);
        defer allocator.free(plugin_var_name);

        try writer.print("\n    .registerPlugin({s})", .{plugin_var_name});
    }
}

/// Convert a plugin name to a valid Zig variable name. Uses the shared
/// identifier rule (identifier.zig) — the same one context.pluginFieldName
/// applies to plugin ids at comptime.
fn pluginVarName(allocator: std.mem.Allocator, plugin_name: []const u8) ![]u8 {
    return identifier.sanitize(allocator, plugin_name);
}

// ============================================================================
// Tests
// ============================================================================

// Test helper for creating plugin structures
// Test helper for creating plugin structures
const PluginTestHelper = struct {
    allocator: std.mem.Allocator,
    plugins: std.ArrayList(PluginInfo),

    fn init(allocator: std.mem.Allocator) PluginTestHelper {
        return .{
            .allocator = allocator,
            .plugins = std.ArrayList(PluginInfo).empty,
        };
    }

    fn deinit(self: *PluginTestHelper) void {
        for (self.plugins.items) |plugin_info| {
            self.allocator.free(plugin_info.name);
            self.allocator.free(plugin_info.import_name);
        }
        self.plugins.deinit(self.allocator);
    }

    fn addLocal(self: *PluginTestHelper, name: []const u8, import_name: []const u8) !void {
        try self.plugins.append(self.allocator, .{
            .name = try self.allocator.dupe(u8, name),
            .import_name = try self.allocator.dupe(u8, import_name),
            .is_local = true,
            .dependency = null,
        });
    }

    fn addExternal(self: *PluginTestHelper, name: []const u8) !void {
        try self.plugins.append(self.allocator, .{
            .name = try self.allocator.dupe(u8, name),
            .import_name = try self.allocator.dupe(u8, name),
            .is_local = false,
            .dependency = null, // In real scenario, this would be from b.lazyDependency
        });
    }
};

fn tcDupePath(a: std.mem.Allocator, path: []const []const u8) ![]const []const u8 {
    const out = try a.alloc([]const u8, path.len);
    for (path, 0..) |p, i| out[i] = try a.dupe(u8, p);
    return out;
}

fn tcCmd(
    a: std.mem.Allocator,
    name: []const u8,
    path: []const []const u8,
    file_path: []const u8,
    command_type: CommandType,
    subcommands: ?std.StringHashMap(DiscoveredCommand),
) !DiscoveredCommand {
    return .{
        .name = try a.dupe(u8, name),
        .path = try tcDupePath(a, path),
        .file_path = try a.dupe(u8, file_path),
        .command_type = command_type,
        .subcommands = subcommands,
    };
}

test "nested imports and registrations share one alphabetical pre-order walk" {
    // Mirrors the real projects/zcli tree: a leaf, an optional group with a
    // nested leaf, and an optional group whose descendants sit under two pure
    // groups. The import block and the .register(...) chain must cover the same
    // commands, name each module identically, and appear in the same order —
    // which is exactly what routing both passes through module_names.flatten
    // guarantees. Insert out of alphabetical order to prove the walk sorts.
    const allocator = std.testing.allocator;
    var commands = DiscoveredCommands.init(allocator);
    defer commands.deinit();

    // gh (optional_group) → add (pure) → workflow (pure) → release (leaf)
    var wf_subs = std.StringHashMap(DiscoveredCommand).init(allocator);
    try wf_subs.put(try allocator.dupe(u8, "release"), try tcCmd(allocator, "release", &.{ "gh", "add", "workflow", "release" }, "gh/add/workflow/release.zig", .leaf, null));
    var ghadd_subs = std.StringHashMap(DiscoveredCommand).init(allocator);
    try ghadd_subs.put(try allocator.dupe(u8, "workflow"), try tcCmd(allocator, "workflow", &.{ "gh", "add", "workflow" }, "gh/add/workflow", .pure_group, wf_subs));
    var gh_subs = std.StringHashMap(DiscoveredCommand).init(allocator);
    try gh_subs.put(try allocator.dupe(u8, "add"), try tcCmd(allocator, "add", &.{ "gh", "add" }, "gh/add", .pure_group, ghadd_subs));
    try commands.root.put(try allocator.dupe(u8, "gh"), try tcCmd(allocator, "gh", &.{"gh"}, "gh/index.zig", .optional_group, gh_subs));

    // init (leaf)
    try commands.root.put(try allocator.dupe(u8, "init"), try tcCmd(allocator, "init", &.{"init"}, "init.zig", .leaf, null));

    // add (optional_group) → command (leaf)
    var add_subs = std.StringHashMap(DiscoveredCommand).init(allocator);
    try add_subs.put(try allocator.dupe(u8, "command"), try tcCmd(allocator, "command", &.{ "add", "command" }, "add/command.zig", .leaf, null));
    try commands.root.put(try allocator.dupe(u8, "add"), try tcCmd(allocator, "add", &.{"add"}, "add/index.zig", .optional_group, add_subs));

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = &.{},
        .app_name = "app",
        .app_version = "1.0.0",
        .app_description = "app",
    };

    const source = try generateComptimeRegistrySource(allocator, commands, config, &.{});
    defer allocator.free(source);

    const expected_imports =
        \\const add_index = @import("add_index");
        \\const add_command = @import("add_command");
        \\const gh_index = @import("gh_index");
        \\const gh_add_workflow_release = @import("gh_add_workflow_release");
        \\const cmd_init = @import("cmd_init");
    ;
    try std.testing.expect(std.mem.indexOf(u8, source, expected_imports) != null);

    const expected_registrations =
        "\n    .register(\"add\", add_index)" ++
        "\n    .register(\"add command\", add_command)" ++
        "\n    .register(\"gh\", gh_index)" ++
        "\n    .register(\"gh add workflow release\", gh_add_workflow_release)" ++
        "\n    .register(\"init\", cmd_init)";
    try std.testing.expect(std.mem.indexOf(u8, source, expected_registrations) != null);
}

test "app metadata is escaped into valid string literals" {
    const allocator = std.testing.allocator;

    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(DiscoveredCommand).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = &.{},
        .app_name = "my-app",
        .app_version = "1.0.0",
        .app_description = "say \"hi\"\nback\\slash",
    };

    const source = try generateComptimeRegistrySource(allocator, commands, config, &.{});
    defer allocator.free(source);

    // Quote, newline, and backslash must all be escaped inside the literal —
    // an unescaped one terminates the string and injects the rest as code.
    try std.testing.expect(std.mem.indexOf(u8, source, ".app_description = \"say \\\"hi\\\"\\nback\\\\slash\",") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "\"say \"hi\"") == null);
}

test "plugin registry generation with imports" {
    const allocator = std.testing.allocator;
    var test_plugins = PluginTestHelper.init(allocator);
    defer test_plugins.deinit();

    try test_plugins.addLocal("logger", "plugins/logger");
    try test_plugins.addExternal("zcli-auth");

    // Create mock discovered commands
    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(DiscoveredCommand).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = test_plugins.plugins.items,
        .app_name = "test-app",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    // Generate registry source
    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        test_plugins.plugins.items,
    );
    defer allocator.free(source);

    // Verify generated content includes plugin imports
    try std.testing.expect(std.mem.indexOf(u8, source, "const logger = @import(\"plugins/logger\");") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const zcli_auth = @import(\"zcli-auth\");") != null);

    // Verify new comptime registry Context generation
    try std.testing.expect(std.mem.indexOf(u8, source, "pub const Context = RegistryType.Context;") != null);

    // Verify registry generation (replaces pipeline generation)
    try std.testing.expect(std.mem.indexOf(u8, source, "const RegistryType = zcli.Registry.init") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".build();") != null);
    // Note: In the new comptime approach, plugins are registered and called through the registry
    // rather than generating complex pipeline code
}

test "plugin import path is escaped into a valid string literal" {
    // main.zig rejects such an external plugin name up front; this is the
    // belt-and-braces guarantee that codegen never emits a raw quote/backslash
    // into `@import("...")` even if a bad import_name reaches it.
    const allocator = std.testing.allocator;
    var test_plugins = PluginTestHelper.init(allocator);
    defer test_plugins.deinit();

    try test_plugins.addExternal("foo\"bar\\baz");

    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(DiscoveredCommand).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = test_plugins.plugins.items,
        .app_name = "test-app",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    const source = try generateComptimeRegistrySource(allocator, commands, config, test_plugins.plugins.items);
    defer allocator.free(source);

    // The quote and backslash must be escaped inside the import literal, never raw.
    try std.testing.expect(std.mem.indexOf(u8, source, "@import(\"foo\\\"bar\\\\baz\")") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "@import(\"foo\"bar") == null);
}

test "plugin name sanitization for imports" {
    const allocator = std.testing.allocator;
    var test_plugins = PluginTestHelper.init(allocator);
    defer test_plugins.deinit();

    // Add plugin with dash in name (should be converted to underscore)
    try test_plugins.addExternal("zcli-help");
    try test_plugins.addExternal("my-custom-plugin");

    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(DiscoveredCommand).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = test_plugins.plugins.items,
        .app_name = "test-app",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        test_plugins.plugins.items,
    );
    defer allocator.free(source);

    // Verify dashes are converted to underscores in variable names
    try std.testing.expect(std.mem.indexOf(u8, source, "const zcli_help = @import(\"zcli-help\");") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const my_custom_plugin = @import(\"my-custom-plugin\");") != null);
}

test "Context extension generation" {
    const allocator = std.testing.allocator;
    var test_plugins = PluginTestHelper.init(allocator);
    defer test_plugins.deinit();

    try test_plugins.addLocal("auth", "plugins/auth");
    try test_plugins.addLocal("logger", "plugins/logger");

    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(DiscoveredCommand).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = test_plugins.plugins.items,
        .app_name = "test-app",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        test_plugins.plugins.items,
    );
    defer allocator.free(source);

    // Verify plugins are registered with the registry
    try std.testing.expect(std.mem.indexOf(u8, source, ".registerPlugin(auth)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".registerPlugin(logger)") != null);

    // Verify new init function signature
    try std.testing.expect(std.mem.indexOf(u8, source, "pub fn init() RegistryType") != null);

    // Note: The new registry approach doesn't need a deinit function
}

test "pipeline composition ordering" {
    const allocator = std.testing.allocator;
    var test_plugins = PluginTestHelper.init(allocator);
    defer test_plugins.deinit();

    // Order matters - last plugin wraps first
    try test_plugins.addLocal("plugin1", "plugins/plugin1");
    try test_plugins.addLocal("plugin2", "plugins/plugin2");
    try test_plugins.addLocal("plugin3", "plugins/plugin3");

    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(DiscoveredCommand).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = test_plugins.plugins.items,
        .app_name = "test-app",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        test_plugins.plugins.items,
    );
    defer allocator.free(source);

    // In the new approach, verify plugins are registered in the correct order
    const plugin1_pos = std.mem.indexOf(u8, source, ".registerPlugin(plugin1)").?;
    const plugin2_pos = std.mem.indexOf(u8, source, ".registerPlugin(plugin2)").?;
    const plugin3_pos = std.mem.indexOf(u8, source, ".registerPlugin(plugin3)").?;

    // They should appear in the order they were added
    try std.testing.expect(plugin1_pos < plugin2_pos);
    try std.testing.expect(plugin2_pos < plugin3_pos);
}

test "Commands struct with plugin commands" {
    const allocator = std.testing.allocator;
    var test_plugins = PluginTestHelper.init(allocator);
    defer test_plugins.deinit();

    try test_plugins.addLocal("auth", "plugins/auth");
    try test_plugins.addExternal("zcli-help");

    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(DiscoveredCommand).init(allocator),
    };
    defer commands.deinit();

    // Add a native command
    var hello_path = try allocator.alloc([]const u8, 1);
    hello_path[0] = try allocator.dupe(u8, "hello");

    const hello_cmd = DiscoveredCommand{
        .name = try allocator.dupe(u8, "hello"),
        .path = hello_path,
        .file_path = try allocator.dupe(u8, "src/commands/hello.zig"),
        .command_type = .leaf,
        .subcommands = null,
    };
    try commands.root.put(try allocator.dupe(u8, "hello"), hello_cmd);

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = test_plugins.plugins.items,
        .app_name = "test-app",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        test_plugins.plugins.items,
    );
    defer allocator.free(source);

    // Verify commands are registered with the registry (new approach)
    try std.testing.expect(std.mem.indexOf(u8, source, "const cmd_hello = @import(\"cmd_hello\");") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".register(\"hello\", cmd_hello)") != null);

    // Verify plugins are also registered (combined approach)
    try std.testing.expect(std.mem.indexOf(u8, source, ".registerPlugin(auth)") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".registerPlugin(zcli_help)") != null);

    // Verify registry is built
    try std.testing.expect(std.mem.indexOf(u8, source, ".build();") != null);

    // Note: The new registry approach handles command discovery differently
}

test "empty plugin list handling" {
    const allocator = std.testing.allocator;

    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(DiscoveredCommand).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = null,
        .plugins = null, // No plugins
        .app_name = "test-app",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        &.{}, // Empty plugin array
    );
    defer allocator.free(source);

    // Should still generate valid code with no plugins
    try std.testing.expect(std.mem.indexOf(u8, source, "pub const Context = RegistryType.Context;") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const RegistryType = zcli.Registry.init") != null);

    // Registry should build successfully even with no plugins
    try std.testing.expect(std.mem.indexOf(u8, source, ".build();") != null);
}

test "generated code structure validation" {
    const allocator = std.testing.allocator;

    // Create test plugin info
    var plugins = std.ArrayList(PluginInfo).empty;
    defer plugins.deinit(allocator);

    try plugins.append(allocator, .{
        .name = try allocator.dupe(u8, "test-plugin"),
        .import_name = try allocator.dupe(u8, "plugins/test"),
        .is_local = true,
        .dependency = null,
    });
    defer allocator.free(plugins.items[0].name);
    defer allocator.free(plugins.items[0].import_name);

    // Create empty commands for simplicity
    var commands = DiscoveredCommands{
        .allocator = allocator,
        .root = std.StringHashMap(DiscoveredCommand).init(allocator),
    };
    defer commands.deinit();

    const config = BuildConfig{
        .commands_dir = "src/commands",
        .plugins_dir = "src/plugins",
        .plugins = plugins.items,
        .app_name = "testapp",
        .app_version = "1.0.0",
        .app_description = "Test app",
    };

    // Generate registry source
    const source = try generateComptimeRegistrySource(
        allocator,
        commands,
        config,
        plugins.items,
    );
    defer allocator.free(source);

    // Validate key structures are present in new registry format
    try std.testing.expect(std.mem.indexOf(u8, source, "pub const Context = RegistryType.Context;") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "const RegistryType = zcli.Registry.init") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".build();") != null);

    // Verify plugins are registered
    try std.testing.expect(std.mem.indexOf(u8, source, ".registerPlugin(") != null);

    // Validate plugin is referenced
    try std.testing.expect(std.mem.indexOf(u8, source, "test_plugin") != null);
}
