const std = @import("std");
const zcli = @import("zcli");
const tree = @import("tree.zig");
const escape = @import("escape.zig");

/// Generate a bash completion script for the given app.
///
/// The generated `_<app>_completions` function:
///   1. builds `cmd_path` = the non-option words between the app name and the
///      cursor, joined into a single `key` (`"${cmd_path[*]}"`);
///   2. if the current word starts with `-`, completes options for `key`
///      (global options always included);
///   3. otherwise completes the child commands (and aliases) of `key`.
///
/// The `key` is the parent path: at the root `key` is empty, after `tasks sprint`
/// it is `"sprint"`. A single `case "$key"` therefore drives every depth with no
/// per-depth arithmetic — the off-by-one/array-expansion bugs of the old design
/// are structurally impossible.
pub fn generate(
    allocator: std.mem.Allocator,
    app_name: []const u8,
    commands: []const zcli.CommandInfo,
    global_options: []const zcli.OptionInfo,
) ![]const u8 {
    var arena_state = std.heap.ArenaAllocator.init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const root = try tree.build(arena, commands);

    var aw: std.Io.Writer.Allocating = .init(allocator);
    errdefer aw.deinit();
    const writer = &aw.writer;

    try writer.print("# bash completion for {s}\n", .{app_name});
    try writer.writeAll("# Generated by zcli-completions plugin\n");
    try writer.writeAll("# Note: requires the bash-completion package for _init_completion.\n\n");

    try writer.print("_{s}_completions() {{\n", .{app_name});
    // Fallback when the bash-completion package (and its _init_completion helper)
    // is not installed: populate cur/prev/words/cword from COMP_WORDS manually.
    try writer.writeAll("    local cur prev words cword\n");
    try writer.writeAll("    if declare -F _init_completion >/dev/null 2>&1; then\n");
    try writer.writeAll("        _init_completion || return\n");
    try writer.writeAll("    else\n");
    try writer.writeAll("        cur=\"${COMP_WORDS[COMP_CWORD]}\"\n");
    try writer.writeAll("        prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n");
    try writer.writeAll("        words=(\"${COMP_WORDS[@]}\")\n");
    try writer.writeAll("        cword=$COMP_CWORD\n");
    try writer.writeAll("    fi\n\n");

    // Build the command path key: non-option words between app name and cursor.
    try writer.writeAll("    local cmd_path=()\n");
    try writer.writeAll("    local i\n");
    try writer.writeAll("    for ((i=1; i<cword; i++)); do\n");
    try writer.writeAll("        if [[ \"${words[i]}\" != -* ]]; then\n");
    try writer.writeAll("            cmd_path+=(\"${words[i]}\")\n");
    try writer.writeAll("        fi\n");
    try writer.writeAll("    done\n");
    // Join into a single word so `case` subjects match single-word patterns.
    try writer.writeAll("    local key=\"${cmd_path[*]}\"\n\n");

    // ---- Option completion ---------------------------------------------------
    try writer.writeAll("    if [[ \"$cur\" == -* ]]; then\n");
    try writer.writeAll("        local opts=\"");
    try writeOptionNames(writer, global_options);
    try writer.writeAll("\"\n");
    try writer.writeAll("        case \"$key\" in\n");
    try writeOptionCases(arena, writer, root);
    try writer.writeAll("        esac\n");
    try writer.writeAll("        COMPREPLY=($(compgen -W \"$opts\" -- \"$cur\"))\n");
    try writer.writeAll("        return 0\n");
    try writer.writeAll("    fi\n\n");

    // ---- Static option-value completion (prev word is an enum/.file/.dir opt) --
    if (hasStaticOptionValues(root, global_options)) {
        try writer.writeAll("    case \"$prev\" in\n");
        try writeStaticOptionValueCases(arena, writer, root, global_options);
        try writer.writeAll("    esac\n\n");
    }

    // ---- Command completion --------------------------------------------------
    try writer.writeAll("    local completions=\"\"\n");
    try writer.writeAll("    case \"$key\" in\n");
    try writeCommandCases(arena, writer, root);
    try writer.writeAll("    esac\n\n");

    const has_dynamic = tree.hasDynamicHook(root) or tree.anyOptionHook(global_options);
    const has_pos_enums = hasPositionalStatic(root);

    try writer.writeAll("    if [[ -n \"$completions\" ]]; then\n");
    try writer.writeAll("        COMPREPLY=($(compgen -W \"$completions\" -- \"$cur\"))\n");
    if (has_dynamic or has_pos_enums) {
        try writer.writeAll("    else\n");
        if (has_dynamic) {
            // Dynamic positional completion: ask the program for live candidates.
            // `__complete` resolves the exact field the cursor is on (returning
            // nothing when there is no hook), so one call covers every position.
            // NUL-framed read (`read -d ''`) so a value may contain spaces/globs;
            // bash keeps only the value (COMPREPLY has no description channel).
            try writer.writeAll("        local __rec\n");
            try writer.writeAll("        while IFS= read -r -d '' __rec; do\n");
            try writer.writeAll("            COMPREPLY+=(\"${__rec%%$'\\t'*}\")\n");
            try writer.writeAll("        done < <(\"${words[0]}\" __complete \"$cword\" -- \"${words[@]}\" 2>/dev/null)\n");
        }
        if (has_pos_enums) {
            // Static enum positionals (first slot). Only when the dynamic pass
            // produced nothing, so a hook always wins for its own field.
            if (has_dynamic) try writer.writeAll("        if [[ ${#COMPREPLY[@]} -eq 0 ]]; then\n");
            try writer.writeAll("        case \"$key\" in\n");
            try writePositionalCases(arena, writer, root);
            try writer.writeAll("        esac\n");
            if (has_dynamic) try writer.writeAll("        fi\n");
        }
    }
    try writer.writeAll("    fi\n");
    try writer.writeAll("    return 0\n");
    try writer.writeAll("}\n\n");

    try writer.print("complete -F _{s}_completions {s}\n", .{ app_name, app_name });

    var al = aw.toArrayList();
    return al.toOwnedSlice(allocator);
}

/// Emit `--name -s ` for each option into a space-separated list.
fn writeOptionNames(writer: anytype, options: []const zcli.OptionInfo) !void {
    for (options) |opt| {
        try writer.print("--{s} ", .{opt.name});
        if (opt.short) |short| try writer.print("-{c} ", .{short});
    }
}

/// Emit a `"path")` case for every node that declares options, appending them to
/// the running `$opts` list (which already holds the global options).
fn writeOptionCases(arena: std.mem.Allocator, writer: anytype, node: *const tree.CommandNode) !void {
    if (node.options.len > 0) {
        try writer.print("            \"{s}\")\n", .{try joinPath(arena, node.path)});
        try writer.writeAll("                opts=\"$opts ");
        try writeOptionNames(writer, node.options);
        try writer.writeAll("\"\n");
        try writer.writeAll("                ;;\n");
    }
    for (node.children) |child| try writeOptionCases(arena, writer, child);
}

/// Emit a `"path")` case for every parent node, listing its child command names
/// and their aliases as the completion set for that path.
fn writeCommandCases(arena: std.mem.Allocator, writer: anytype, node: *const tree.CommandNode) !void {
    if (node.children.len > 0) {
        try writer.print("        \"{s}\")\n", .{try joinPath(arena, node.path)});
        try writer.writeAll("            completions=\"");
        for (node.children) |child| {
            try writer.print("{s} ", .{child.name});
            for (child.aliases) |alias| try writer.print("{s} ", .{alias});
        }
        try writer.writeAll("\"\n");
        try writer.writeAll("            ;;\n");
    }
    for (node.children) |child| try writeCommandCases(arena, writer, child);
}

/// The `compgen` operand for a field's STATIC completion — its enum choices
/// (`-W "a b c"`) or the `.file`/`.dir` builtin (`-f`/`-d`) — or null when the
/// field completes dynamically (a hook, handled by the callback branch) or not at
/// all. Arena-owned.
fn staticCompgenArgs(arena: std.mem.Allocator, enum_values: ?[]const []const u8, complete: ?zcli.completion.Spec) !?[]const u8 {
    if (complete) |c| {
        switch (c) {
            .hook => return null,
            .file => return "-f",
            .dir => return "-d",
        }
    }
    if (enum_values) |values| {
        var out = std.ArrayList(u8).empty;
        try out.appendSlice(arena, "-W \"");
        for (values, 0..) |v, idx| {
            if (idx > 0) try out.append(arena, ' ');
            try out.appendSlice(arena, v);
        }
        try out.append(arena, '"');
        return out.items;
    }
    return null;
}

/// Emit a `"path")` case offering a leaf command's FIRST positional's static
/// completion (enum choices or a `.file`/`.dir` builtin). Matching on the exact
/// command path means the case fires at that first positional. A hook positional
/// contributes no case (the dynamic callback branch handles it).
fn writePositionalCases(arena: std.mem.Allocator, writer: anytype, node: *const tree.CommandNode) !void {
    if (node.isLeaf() and node.args.len > 0) {
        if (try staticCompgenArgs(arena, node.args[0].enum_values, node.args[0].complete)) |gen| {
            try writer.print("            \"{s}\")\n", .{try joinPath(arena, node.path)});
            try writer.print("                COMPREPLY=($(compgen {s} -- \"$cur\"))\n", .{gen});
            try writer.writeAll("                ;;\n");
        }
    }
    for (node.children) |child| try writePositionalCases(arena, writer, child);
}

/// True if any leaf command's first positional has a static completion (enum or
/// `.file`/`.dir`) — i.e. we need a positional `case "$key"` block.
fn hasPositionalStatic(node: *const tree.CommandNode) bool {
    if (node.isLeaf() and node.args.len > 0) {
        const a = node.args[0];
        if (a.enum_values != null) return true;
        if (a.complete) |c| return c != .hook;
    }
    for (node.children) |child| if (hasPositionalStatic(child)) return true;
    return false;
}

/// True if any option (command or global) takes a value with static completion
/// (enum or `.file`/`.dir`) — i.e. we need a `$prev` case for it.
fn hasStaticOptionValues(node: *const tree.CommandNode, global_options: []const zcli.OptionInfo) bool {
    if (anyStaticOptionValue(global_options)) return true;
    if (anyStaticOptionValue(node.options)) return true;
    for (node.children) |child| if (hasStaticOptionValues(child, global_options)) return true;
    return false;
}

fn anyStaticOptionValue(options: []const zcli.OptionInfo) bool {
    for (options) |opt| {
        if (opt.enum_values != null) return true;
        if (opt.complete) |c| if (c != .hook) return true;
    }
    return false;
}

/// Emit `--name|-s)` cases whose value completes statically (enum choices, or the
/// `.file`/`.dir` builtin), keyed on the previous word regardless of command path
/// (a small, pragmatic simplification — option names rarely collide). Hook options
/// are omitted here; the dynamic callback branch resolves them.
fn writeStaticOptionValueCases(arena: std.mem.Allocator, writer: anytype, node: *const tree.CommandNode, global_options: []const zcli.OptionInfo) !void {
    try writeStaticOptionValueCasesFor(arena, writer, global_options);
    try writeStaticOptionValueCasesRec(arena, writer, node);
}

fn writeStaticOptionValueCasesRec(arena: std.mem.Allocator, writer: anytype, node: *const tree.CommandNode) !void {
    try writeStaticOptionValueCasesFor(arena, writer, node.options);
    for (node.children) |child| try writeStaticOptionValueCasesRec(arena, writer, child);
}

fn writeStaticOptionValueCasesFor(arena: std.mem.Allocator, writer: anytype, options: []const zcli.OptionInfo) !void {
    for (options) |opt| {
        const gen = (try staticCompgenArgs(arena, opt.enum_values, opt.complete)) orelse continue;
        try writer.print("        --{s}", .{opt.name});
        if (opt.short) |short| try writer.print("|-{c}", .{short});
        try writer.writeAll(")\n");
        try writer.print("            COMPREPLY=($(compgen {s} -- \"$cur\"))\n", .{gen});
        try writer.writeAll("            return 0\n");
        try writer.writeAll("            ;;\n");
    }
}

/// Join a command path with spaces (`["sprint","list"]` → `"sprint list"`).
fn joinPath(arena: std.mem.Allocator, path: []const []const u8) ![]const u8 {
    return std.mem.join(arena, " ", path);
}
