const std = @import("std");
const zcli = @import("zcli");
const tree = @import("tree.zig");
const escape = @import("escape.zig");

/// Generate a fish completion script for the given app.
///
/// Fish matches completions on conditions. The old script used
/// `__fish_seen_subcommand_from`, which matches a token *anywhere* on the line —
/// so root `list` and `sprint list` collide. Instead we emit a generated helper,
/// `__fish_<app>_using_command`, that inspects the positional token sequence
/// (`commandline -opc`, options stripped) and matches only when the command path
/// is exactly a given prefix. Every subcommand and option condition uses it.
///
/// All descriptions/values are routed through `escape.fish`.
pub fn generate(
    allocator: std.mem.Allocator,
    app_name: []const u8,
    commands: []const zcli.CommandInfo,
    global_options: []const zcli.OptionInfo,
) ![]const u8 {
    var arena_state = std.heap.ArenaAllocator.init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const root = try tree.build(arena, commands);

    var aw: std.Io.Writer.Allocating = .init(allocator);
    errdefer aw.deinit();
    const writer = &aw.writer;

    try writer.print("# fish completion for {s}\n", .{app_name});
    try writer.writeAll("# Generated by zcli-completions plugin\n\n");

    // Positional command-path matcher. Args are the expected command path
    // segments; succeeds only when the non-option tokens after the command name
    // equal exactly that path (so `sprint list` never matches root `list`).
    try writer.print(
        \\function __fish_{s}_using_command
        \\    set -l cmd (commandline -opc)
        \\    set -l parts
        \\    # Drop the program name, then keep only non-option tokens.
        \\    for tok in $cmd[2..-1]
        \\        switch $tok
        \\            case '-*'
        \\            case '*'
        \\                set -a parts $tok
        \\        end
        \\    end
        \\    test (count $parts) -eq (count $argv); or return 1
        \\    for i in (seq (count $argv))
        \\        test "$parts[$i]" = "$argv[$i]"; or return 1
        \\    end
        \\    return 0
        \\end
        \\
        \\
    , .{app_name});

    // Global options: available everywhere, no condition.
    for (global_options) |opt| {
        try writeOption(arena, writer, app_name, null, opt);
    }
    if (global_options.len > 0) try writer.writeAll("\n");

    // Subcommands + per-command options, walking the tree.
    try writeNode(arena, writer, app_name, root);

    var al = aw.toArrayList();
    return al.toOwnedSlice(allocator);
}

/// Emit completions for `node`'s children (as subcommands offered when the line
/// is exactly at `node`'s path), then recurse. Also emits each child's options.
fn writeNode(
    arena: std.mem.Allocator,
    writer: anytype,
    app_name: []const u8,
    node: *const tree.CommandNode,
) !void {
    // Leaf positional completion. The `using_command` condition matches only when
    // the token sequence equals this exact path — i.e. the cursor is at the first
    // positional. `-f` there suppresses fish's default file completion (so a
    // command that takes an id doesn't dump the CWD); an enum arg additionally
    // offers its choices.
    if (node.isLeaf() and node.path.len > 0) {
        try writePositional(arena, writer, app_name, node);
    }

    // Offer this node's children as subcommands, conditioned on being exactly at
    // this node's path (empty path for the root → the bare `-c` condition).
    for (node.children) |child| {
        try writer.print("complete -c {s} -f", .{app_name});
        try writeCondition(arena, writer, app_name, node.path);
        // A subcommand takes no value itself. Fish uses only the last `-a`, so
        // offer the name and any aliases as one space-separated argument list.
        try writer.print(" -a '{s}", .{child.name});
        for (child.aliases) |alias| try writer.print(" {s}", .{alias});
        try writer.writeAll("'");
        if (child.description) |d| {
            const esc = try escape.fish(arena, d);
            try writer.print(" -d '{s}'", .{esc});
        }
        try writer.writeAll("\n");
    }
    if (node.children.len > 0) try writer.writeAll("\n");

    // Emit options for each child, conditioned on being at that child's path.
    for (node.children) |child| {
        for (child.options) |opt| {
            try writeOption(arena, writer, app_name, child.path, opt);
        }
        if (child.options.len > 0) try writer.writeAll("\n");
    }

    for (node.children) |child| try writeNode(arena, writer, app_name, child);
}

/// Emit the leaf's first-positional completion: always `-f` (no file dump) at
/// the command's own path, plus `-a`/`-d` for an enum first positional.
fn writePositional(
    arena: std.mem.Allocator,
    writer: anytype,
    app_name: []const u8,
    node: *const tree.CommandNode,
) !void {
    try writer.print("complete -c {s} -f", .{app_name});
    try writeCondition(arena, writer, app_name, node.path);

    if (node.args.len > 0) {
        const arg = node.args[0];
        if (arg.enum_values) |values| {
            try writer.writeAll(" -a '");
            for (values, 0..) |v, idx| {
                if (idx > 0) try writer.writeByte(' ');
                const esc = try escape.fish(arena, v);
                try writer.writeAll(esc);
            }
            try writer.writeAll("'");
            if (arg.description) |d| {
                const esc = try escape.fish(arena, d);
                try writer.print(" -d '{s}'", .{esc});
            }
        }
    }
    try writer.writeAll("\n");
}

/// Emit one `complete` directive for an option. `path` null means global (no
/// condition); otherwise the option is offered only when the line is at `path`.
fn writeOption(
    arena: std.mem.Allocator,
    writer: anytype,
    app_name: []const u8,
    path: ?[]const []const u8,
    opt: zcli.OptionInfo,
) !void {
    try writer.print("complete -c {s}", .{app_name});
    if (path) |p| try writeCondition(arena, writer, app_name, p);

    if (opt.short) |short| try writer.print(" -s {c}", .{short});
    try writer.print(" -l {s}", .{opt.name});

    if (opt.description) |desc| {
        const esc = try escape.fish(arena, desc);
        try writer.print(" -d '{s}'", .{esc});
    }

    if (opt.enum_values) |values| {
        // -x: requires an argument AND forbids file completion; -a lists choices.
        try writer.writeAll(" -x -a '");
        for (values, 0..) |v, idx| {
            if (idx > 0) try writer.writeByte(' ');
            const esc = try escape.fish(arena, v);
            try writer.writeAll(esc);
        }
        try writer.writeAll("'");
    } else if (opt.takes_value) {
        try writer.writeAll(" -r");
    }
    try writer.writeAll("\n");
}

/// Append the positional condition for `path`. Empty path → the plain condition
/// that no subcommand has been entered yet.
fn writeCondition(
    arena: std.mem.Allocator,
    writer: anytype,
    app_name: []const u8,
    path: []const []const u8,
) !void {
    try writer.print(" -n '__fish_{s}_using_command", .{app_name});
    for (path) |part| {
        const esc = try escape.fish(arena, part);
        try writer.print(" {s}", .{esc});
    }
    try writer.writeAll("'");
}
