const std = @import("std");
const zcli = @import("zcli");
const tree = @import("tree.zig");
const escape = @import("escape.zig");

/// Generate a PowerShell completion script for the given app.
///
/// PowerShell native completion is registered with a single
/// `Register-ArgumentCompleter -Native` scriptblock. The scriptblock receives the
/// word being completed, the parsed command AST, and the cursor offset; from those
/// it reconstructs the command path (`$key`, the non-option words before the
/// cursor) and the previous token (`$prev`), exactly mirroring the bash generator's
/// `case "$key"`/`$prev` structure.
///
/// Feature parity with the other shells:
///   - subcommands (+ aliases) and option names walk the static command tree,
///   - enum options/positionals offer their choices, `.file`/`.dir` builtins call
///     PowerShell's `CompleteFilename` (dir-filtered for `.dir`),
///   - dynamic `.complete` hooks invoke `<app> __complete <cword> -- <words…>` and
///     split the NUL-framed wire output (see `wire.zig`) into candidates,
///   - descriptions become `[CompletionResult]` tooltips (PowerShell DISPLAYS
///     these, unlike bash).
///
/// EVERY interpolated identifier is routed through `escape.powershell` (single-quote
/// doubling), so a value can never break out of its `'…'` literal.
pub fn generate(
    allocator: std.mem.Allocator,
    app_name: []const u8,
    commands: []const zcli.CommandInfo,
    global_options: []const zcli.OptionInfo,
) ![]const u8 {
    var arena_state = std.heap.ArenaAllocator.init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const root = try tree.build(arena, commands);
    const esc_app = try escape.powershell(arena, app_name);

    var aw: std.Io.Writer.Allocating = .init(allocator);
    errdefer aw.deinit();
    const writer = &aw.writer;

    try writer.print("# powershell completion for {s}\n", .{app_name});
    try writer.writeAll("# Generated by zcli-completions plugin\n\n");

    try writer.print("Register-ArgumentCompleter -Native -CommandName '{s}' -ScriptBlock {{\n", .{esc_app});
    try writer.writeAll("    param($wordToComplete, $commandAst, $cursorPosition)\n\n");

    try writePreamble(arena, writer, esc_app, global_options);

    // 1. Option-name completion (the current word starts with '-').
    try writeOptionNameBlock(arena, writer, root, global_options);

    // 2. Static option-value completion (the previous word is an enum/.file/.dir
    //    option). Hook options fall through to the dynamic pass below.
    if (hasStaticOptionValues(root, global_options)) {
        try writeStaticOptionValueBlock(arena, writer, root, global_options);
    }

    // 3. Subcommand completion, keyed on the command path.
    try writeSubcommandBlock(arena, writer, root);

    // 4. Dynamic positional/option-value completion via `__complete` (emitted only
    //    when some field declares a `.complete` function hook).
    const has_dynamic = tree.hasDynamicHook(root) or tree.anyOptionHook(global_options);
    if (has_dynamic) try writeDynamicBlock(writer);

    // 5. Static positional completion (enum choices or a `.file`/`.dir` builtin),
    //    offered only when the dynamic pass produced nothing (a hook always wins).
    if (hasPositionalStatic(root)) try writePositionalBlock(arena, writer, root);

    try writer.writeAll("    $results\n");
    try writer.writeAll("}\n");

    var al = aw.toArrayList();
    return al.toOwnedSlice(allocator);
}

/// Emit the shared preamble: reconstruct `$key`/`$prev`/`$dynWords`/`$cword` from
/// the AST and define the `Add-Result`/`Complete-*` helpers every block uses.
fn writePreamble(arena: std.mem.Allocator, writer: anytype, esc_app: []const u8, global_options: []const zcli.OptionInfo) !void {
    try writer.writeAll("    $elements = $commandAst.CommandElements\n");
    try writer.print("    $exe = if ($elements.Count -gt 0) {{ $elements[0].Extent.Text }} else {{ '{s}' }}\n\n", .{esc_app});

    // Walk the tokens that lie fully before the word being completed. Option words
    // are skipped for `$key` (the command path) but kept for `$dynWords` (passed to
    // `__complete`). `$prev` is the token immediately before the completion word.
    // A value-taking global option (`--config x.json`) is followed by its VALUE,
    // which is NOT a command word — skip it for `$key` (but keep it in `$dynWords`
    // and as `$prev`). The `--opt=value` form carries its value in the same token,
    // already excluded from `$key` as an option word.
    const has_value_opt = anyValueTakingOption(global_options);
    try writer.writeAll("    $path = @()\n");
    try writer.writeAll("    $prev = ''\n");
    try writer.print("    $dynWords = @('{s}')\n", .{esc_app});
    if (has_value_opt) try writer.writeAll("    $skipVal = $false\n");
    try writer.writeAll("    for ($i = 1; $i -lt $elements.Count; $i++) {\n");
    try writer.writeAll("        $el = $elements[$i]\n");
    try writer.writeAll("        if ($el.Extent.StartOffset -ge $cursorPosition) { break }\n");
    try writer.writeAll("        if ($el.Extent.EndOffset -ge $cursorPosition) { break }\n");
    try writer.writeAll("        $t = $el.Extent.Text\n");
    try writer.writeAll("        $dynWords += $t\n");
    try writer.writeAll("        $prev = $t\n");
    if (has_value_opt) {
        try writer.writeAll("        if ($skipVal) { $skipVal = $false }\n");
        try writer.writeAll("        elseif ($t.StartsWith('-')) {\n");
        try writer.writeAll("            switch -CaseSensitive ($t) {\n");
        try writeValueOptionCasesPS(arena, writer, global_options);
        try writer.writeAll("            }\n");
        try writer.writeAll("        }\n");
        try writer.writeAll("        else { $path += $t }\n");
    } else {
        try writer.writeAll("        if (-not $t.StartsWith('-')) { $path += $t }\n");
    }
    try writer.writeAll("    }\n");
    try writer.writeAll("    $key = ($path -join ' ')\n");
    try writer.writeAll("    $dynWords += $wordToComplete\n");
    try writer.writeAll("    $cword = $dynWords.Count - 1\n\n");

    try writer.writeAll("    $results = [System.Collections.Generic.List[System.Management.Automation.CompletionResult]]::new()\n");
    try writer.writeAll("    $seen = [System.Collections.Generic.HashSet[string]]::new()\n");
    try writer.writeAll("    function Add-Result([string]$text, [string]$tip, [string]$kind) {\n");
    try writer.writeAll("        if (-not $seen.Add($text)) { return }\n");
    try writer.writeAll("        if ([string]::IsNullOrEmpty($tip)) { $tip = $text }\n");
    try writer.writeAll("        [void]$results.Add([System.Management.Automation.CompletionResult]::new($text, $text, $kind, $tip))\n");
    try writer.writeAll("    }\n");
    try writer.writeAll("    function Complete-Option([string]$n, [string]$d) {\n");
    try writer.writeAll("        if ($n.StartsWith($wordToComplete)) { Add-Result $n $d 'ParameterName' }\n");
    try writer.writeAll("    }\n");
    try writer.writeAll("    function Complete-Command([string]$n, [string]$d) {\n");
    try writer.writeAll("        if ($n.StartsWith($wordToComplete)) { Add-Result $n $d 'Command' }\n");
    try writer.writeAll("    }\n");
    try writer.writeAll("    function Complete-Value([string]$v) {\n");
    try writer.writeAll("        if ($v.StartsWith($wordToComplete)) { Add-Result $v $v 'ParameterValue' }\n");
    try writer.writeAll("    }\n");
    try writer.writeAll("    function Complete-Files([bool]$dirsOnly) {\n");
    try writer.writeAll("        $fc = [System.Management.Automation.CompletionCompleters]::CompleteFilename($wordToComplete)\n");
    try writer.writeAll("        if ($dirsOnly) { $fc = $fc | Where-Object { $_.ResultType -eq [System.Management.Automation.CompletionResultType]::ProviderContainer } }\n");
    try writer.writeAll("        foreach ($f in $fc) { [void]$results.Add($f) }\n");
    try writer.writeAll("    }\n\n");
}

/// True if any option in the set takes a value (so a bare `--opt <value>` on the
/// command line consumes the following word — which must not be mistaken for a
/// command word when reconstructing the command path).
fn anyValueTakingOption(options: []const zcli.OptionInfo) bool {
    for (options) |opt| if (opt.takes_value) return true;
    return false;
}

/// Emit `'--name' { $skipVal = $true }` (and the short form) switch cases for
/// every value-taking option — the look-ahead that keeps an option's VALUE out
/// of the command path. Names are escaped for their single-quoted labels.
fn writeValueOptionCasesPS(arena: std.mem.Allocator, writer: anytype, options: []const zcli.OptionInfo) !void {
    for (options) |opt| {
        if (!opt.takes_value) continue;
        const esc_name = try escape.powershell(arena, opt.name);
        try writer.print("                '--{s}' {{ $skipVal = $true }}\n", .{esc_name});
        if (opt.short) |short| {
            const esc_short = try escape.powershell(arena, &[_]u8{short});
            try writer.print("                '-{s}' {{ $skipVal = $true }}\n", .{esc_short});
        }
    }
}

// ============================================================================
// 1. Option names
// ============================================================================

fn writeOptionNameBlock(
    arena: std.mem.Allocator,
    writer: anytype,
    root: *const tree.CommandNode,
    global_options: []const zcli.OptionInfo,
) !void {
    try writer.writeAll("    if ($wordToComplete.StartsWith('-')) {\n");
    // Global options: offered at every command path.
    for (global_options) |opt| try writeCompleteOption(arena, writer, "        ", opt);
    // Per-command options, keyed on the command path.
    try writer.writeAll("        switch -CaseSensitive ($key) {\n");
    try writeOptionNameCases(arena, writer, root);
    try writer.writeAll("        }\n");
    try writer.writeAll("        $results\n");
    try writer.writeAll("        return\n");
    try writer.writeAll("    }\n\n");
}

fn writeOptionNameCases(arena: std.mem.Allocator, writer: anytype, node: *const tree.CommandNode) !void {
    if (node.options.len > 0) {
        try writer.print("            '{s}' {{\n", .{try escKey(arena, node.path)});
        for (node.options) |opt| try writeCompleteOption(arena, writer, "                ", opt);
        try writer.writeAll("            }\n");
    }
    for (node.children) |child| try writeOptionNameCases(arena, writer, child);
}

/// Emit `Complete-Option '--name' 'desc'` (and the short form) for one option.
fn writeCompleteOption(arena: std.mem.Allocator, writer: anytype, indent: []const u8, opt: zcli.OptionInfo) !void {
    const esc_name = try escape.powershell(arena, opt.name);
    const esc_desc = if (opt.description) |d| try escape.powershell(arena, d) else "";
    try writer.print("{s}Complete-Option '--{s}' '{s}'\n", .{ indent, esc_name, esc_desc });
    if (opt.short) |short| {
        const esc_short = try escape.powershell(arena, &[_]u8{short});
        try writer.print("{s}Complete-Option '-{s}' '{s}'\n", .{ indent, esc_short, esc_desc });
    }
}

// ============================================================================
// 2. Static option values (prev word is an enum / .file / .dir option)
// ============================================================================

fn writeStaticOptionValueBlock(
    arena: std.mem.Allocator,
    writer: anytype,
    root: *const tree.CommandNode,
    global_options: []const zcli.OptionInfo,
) !void {
    // Gather every static-value option (global + all commands), deduped by long
    // name — matching bash, `$prev` is keyed by option name regardless of path.
    var seen = std.ArrayList([]const u8).empty;
    try writer.writeAll("    switch -CaseSensitive ($prev) {\n");
    try writeStaticOptionValueCasesFor(arena, writer, &seen, global_options);
    try writeStaticOptionValueCasesRec(arena, writer, &seen, root);
    try writer.writeAll("    }\n\n");
}

fn writeStaticOptionValueCasesRec(arena: std.mem.Allocator, writer: anytype, seen: *std.ArrayList([]const u8), node: *const tree.CommandNode) !void {
    try writeStaticOptionValueCasesFor(arena, writer, seen, node.options);
    for (node.children) |child| try writeStaticOptionValueCasesRec(arena, writer, seen, child);
}

fn writeStaticOptionValueCasesFor(arena: std.mem.Allocator, writer: anytype, seen: *std.ArrayList([]const u8), options: []const zcli.OptionInfo) !void {
    for (options) |opt| {
        if (!isStaticValueOption(opt)) continue;
        var dup = false;
        for (seen.items) |n| if (std.mem.eql(u8, n, opt.name)) {
            dup = true;
            break;
        };
        if (dup) continue;
        try seen.append(arena, opt.name);

        const esc_name = try escape.powershell(arena, opt.name);
        // A body shared by the long and short forms.
        try writer.print("        '--{s}' {{\n", .{esc_name});
        try writeOptionValueBody(arena, writer, opt);
        try writer.writeAll("        }\n");
        if (opt.short) |short| {
            const esc_short = try escape.powershell(arena, &[_]u8{short});
            try writer.print("        '-{s}' {{\n", .{esc_short});
            try writeOptionValueBody(arena, writer, opt);
            try writer.writeAll("        }\n");
        }
    }
}

fn writeOptionValueBody(arena: std.mem.Allocator, writer: anytype, opt: zcli.OptionInfo) !void {
    if (opt.complete) |c| switch (c) {
        .hook => {}, // never reached: hooks are not static-value options
        .file => try writer.writeAll("            Complete-Files $false\n"),
        .dir => try writer.writeAll("            Complete-Files $true\n"),
    } else if (opt.enum_values) |values| {
        for (values) |v| {
            const esc = try escape.powershell(arena, v);
            try writer.print("            Complete-Value '{s}'\n", .{esc});
        }
    }
    try writer.writeAll("            $results\n");
    try writer.writeAll("            return\n");
}

// ============================================================================
// 3. Subcommands
// ============================================================================

fn writeSubcommandBlock(arena: std.mem.Allocator, writer: anytype, root: *const tree.CommandNode) !void {
    try writer.writeAll("    switch -CaseSensitive ($key) {\n");
    try writeSubcommandCases(arena, writer, root);
    try writer.writeAll("    }\n");
    try writer.writeAll("    if ($results.Count -gt 0) { $results; return }\n\n");
}

fn writeSubcommandCases(arena: std.mem.Allocator, writer: anytype, node: *const tree.CommandNode) !void {
    if (node.children.len > 0) {
        try writer.print("        '{s}' {{\n", .{try escKey(arena, node.path)});
        for (node.children) |child| {
            const esc_name = try escape.powershell(arena, child.name);
            const esc_desc = if (child.description) |d| try escape.powershell(arena, d) else "";
            try writer.print("            Complete-Command '{s}' '{s}'\n", .{ esc_name, esc_desc });
            for (child.aliases) |alias| {
                const esc_alias = try escape.powershell(arena, alias);
                try writer.print("            Complete-Command '{s}' '{s}'\n", .{ esc_alias, esc_desc });
            }
        }
        try writer.writeAll("        }\n");
    }
    for (node.children) |child| try writeSubcommandCases(arena, writer, child);
}

// ============================================================================
// 4. Dynamic completion via `__complete`
// ============================================================================

/// Emit the dynamic block: invoke `<app> __complete <cword> -- <words…>`, join its
/// native output back into one string (PowerShell splits native stdout on
/// newlines; joining with "`n" restores it for the common no-newline case), split
/// on NUL — the FIRST record is the directive, every record after it is a
/// `value` optionally `\t description` candidate — then honour an `also_*`
/// directive by adding native file/dir completion.
fn writeDynamicBlock(writer: anytype) !void {
    try writer.writeAll("    try {\n");
    try writer.writeAll("        $raw = @(& $exe __complete $cword '--' @dynWords 2>$null)\n");
    try writer.writeAll("        $records = ($raw -join \"`n\") -split \"`0\"\n");
    try writer.writeAll("        if ($records.Count -ge 1) {\n");
    try writer.writeAll("            $directive = $records[0]\n");
    try writer.writeAll("            for ($r = 1; $r -lt $records.Count; $r++) {\n");
    try writer.writeAll("                $rec = $records[$r]\n");
    try writer.writeAll("                if ($rec.Length -eq 0) { continue }\n");
    try writer.writeAll("                $tab = $rec.IndexOf(\"`t\")\n");
    try writer.writeAll("                if ($tab -ge 0) {\n");
    try writer.writeAll("                    Add-Result $rec.Substring(0, $tab) $rec.Substring($tab + 1) 'ParameterValue'\n");
    try writer.writeAll("                } else {\n");
    try writer.writeAll("                    Add-Result $rec $rec 'ParameterValue'\n");
    try writer.writeAll("                }\n");
    try writer.writeAll("            }\n");
    try writer.writeAll("            if ($directive -eq 'also_files') { Complete-Files $false }\n");
    try writer.writeAll("            elseif ($directive -eq 'also_dirs') { Complete-Files $true }\n");
    try writer.writeAll("        }\n");
    try writer.writeAll("    } catch { }\n\n");
}

// ============================================================================
// 5. Static positional completion (enum / .file / .dir)
// ============================================================================

fn writePositionalBlock(arena: std.mem.Allocator, writer: anytype, root: *const tree.CommandNode) !void {
    try writer.writeAll("    if ($results.Count -eq 0) {\n");
    try writer.writeAll("        switch -CaseSensitive ($key) {\n");
    try writePositionalCases(arena, writer, root);
    try writer.writeAll("        }\n");
    try writer.writeAll("    }\n\n");
}

fn writePositionalCases(arena: std.mem.Allocator, writer: anytype, node: *const tree.CommandNode) !void {
    if (node.isLeaf() and node.args.len > 0 and positionalIsStatic(node.args[0])) {
        try writer.print("            '{s}' {{\n", .{try escKey(arena, node.path)});
        const arg = node.args[0];
        if (arg.complete) |c| switch (c) {
            .hook => {},
            .file => try writer.writeAll("                Complete-Files $false\n"),
            .dir => try writer.writeAll("                Complete-Files $true\n"),
        } else if (arg.enum_values) |values| {
            for (values) |v| {
                const esc = try escape.powershell(arena, v);
                try writer.print("                Complete-Value '{s}'\n", .{esc});
            }
        }
        try writer.writeAll("            }\n");
    }
    for (node.children) |child| try writePositionalCases(arena, writer, child);
}

// ============================================================================
// Shared predicates (mirroring bash.zig's static/dynamic classification)
// ============================================================================

/// True for an option whose value completes STATICALLY (enum choices or a
/// `.file`/`.dir` builtin) — i.e. it belongs in the `$prev` switch. Hook options
/// are resolved by the dynamic pass instead.
fn isStaticValueOption(opt: zcli.OptionInfo) bool {
    if (opt.complete) |c| return c != .hook;
    return opt.enum_values != null;
}

/// True for a positional whose FIRST-slot value completes statically.
fn positionalIsStatic(arg: zcli.ArgInfo) bool {
    if (arg.complete) |c| return c != .hook;
    return arg.enum_values != null;
}

fn hasStaticOptionValues(node: *const tree.CommandNode, global_options: []const zcli.OptionInfo) bool {
    for (global_options) |opt| if (isStaticValueOption(opt)) return true;
    for (node.options) |opt| if (isStaticValueOption(opt)) return true;
    for (node.children) |child| if (hasStaticOptionValues(child, global_options)) return true;
    return false;
}

fn hasPositionalStatic(node: *const tree.CommandNode) bool {
    if (node.isLeaf() and node.args.len > 0 and positionalIsStatic(node.args[0])) return true;
    for (node.children) |child| if (hasPositionalStatic(child)) return true;
    return false;
}

/// The command path joined with a space and escaped for a single-quoted `switch`
/// label (the root's empty path yields `''`).
fn escKey(arena: std.mem.Allocator, path: []const []const u8) ![]const u8 {
    const joined = try std.mem.join(arena, " ", path);
    return escape.powershell(arena, joined);
}
