const std = @import("std");
const zcli = @import("zcli");
const tree = @import("tree.zig");
const escape = @import("escape.zig");

/// Generate a zsh completion script for the given app.
///
/// This is the reference generator: its `_arguments`/`_describe`/nested
/// `case $line[N]` output is the behaviour the bash and fish generators mirror.
/// It renders purely over the shared `tree.CommandNode` structure and routes all
/// descriptions/values through `escape.zsh`.
pub fn generate(
    allocator: std.mem.Allocator,
    app_name: []const u8,
    commands: []const zcli.CommandInfo,
    global_options: []const zcli.OptionInfo,
) ![]const u8 {
    var arena_state = std.heap.ArenaAllocator.init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const root = try tree.build(arena, commands);

    var aw: std.Io.Writer.Allocating = .init(allocator);
    errdefer aw.deinit();
    const writer = &aw.writer;

    const needs_dynamic = tree.hasDynamicHook(root) or tree.anyOptionHook(global_options);

    try writer.print("#compdef {s}\n", .{app_name});
    try writer.print("# zsh completion for {s}\n", .{app_name});
    try writer.writeAll("# Generated by zcli-completions plugin\n\n");

    // Dynamic-completion callback helper (ADR-0026), emitted only when some field
    // (arg or option) declares a `.complete` function hook.
    if (needs_dynamic) try writeDynamicHelper(writer, app_name);

    try writer.print("_{s}() {{\n", .{app_name});
    try writer.writeAll("    local curcontext=\"$curcontext\" line state\n");
    try writer.writeAll("    typeset -A opt_args\n");

    // Capture the FULL command line before `_arguments` narrows `$words`/`$CURRENT`
    // to a sub-context: the dynamic helper (called from a positional or option
    // action) needs the whole line and the real cursor index to call `__complete`.
    if (needs_dynamic) {
        try writer.print("    typeset -ga _{s}_words=(\"${{words[@]}}\")\n", .{app_name});
        try writer.print("    typeset -g _{s}_current=$CURRENT\n", .{app_name});
    }
    try writer.writeAll("\n");

    // Top-level _arguments: global options + the root command's own options
    // (the root group's index, if any — ADR-0029) + a command slot + the rest.
    try writer.writeAll("    _arguments -S -C \\\n");
    try writeOptionSpecs(arena, writer, app_name, "        ", global_options);
    try writeOptionSpecs(arena, writer, app_name, "        ", root.options);
    try writer.writeAll("        '1: :->command' \\\n");
    try writer.writeAll("        '*::arg:->args'\n\n");

    try writer.writeAll("    case $state in\n");

    // command state: list root commands.
    try writer.writeAll("        command)\n");
    try writer.writeAll("            local -a commands\n");
    try writer.writeAll("            commands=(\n");
    try writeDescribeEntries(arena, writer, "                ", root.children);
    try writer.writeAll("            )\n");
    try writer.writeAll("            _describe 'command' commands\n");
    try writer.writeAll("            ;;\n");

    // args state: dispatch on the entered subcommand path.
    try writer.writeAll("        args)\n");
    try writeArgsDispatch(arena, writer, app_name, root, 1);
    try writer.writeAll("            ;;\n");

    try writer.writeAll("    esac\n");
    try writer.writeAll("}\n\n");

    try writer.print("_{s} \"$@\"\n", .{app_name});

    var al = aw.toArrayList();
    return al.toOwnedSlice(allocator);
}

/// Emit the `case $line[depth] in … esac` block that handles each child of
/// `node`: recurse into groups, or emit option/arg completions for leaves.
fn writeArgsDispatch(
    arena: std.mem.Allocator,
    writer: anytype,
    app_name: []const u8,
    node: *const tree.CommandNode,
    depth: usize,
) !void {
    const indent = try repeat(arena, "    ", depth + 2);
    try writer.print("{s}case $line[{d}] in\n", .{ indent, depth });

    for (node.children) |child| {
        // Match the child by name or any alias. Single-quoted so a name with a
        // glob/command-substitution metacharacter is a literal pattern, not code.
        try writer.print("{s}    '{s}'", .{ indent, try danceSingleQuotes(arena, child.name) });
        for (child.aliases) |alias| try writer.print("|'{s}'", .{try danceSingleQuotes(arena, alias)});
        try writer.writeAll(")\n");

        if (child.children.len > 0) {
            // Group: recurse to dispatch on the next path element.
            try writeArgsDispatch(arena, writer, app_name, child, depth + 1);
        } else {
            // Leaf: complete this command's options and positional args.
            try writeLeafArguments(arena, writer, app_name, indent, child);
        }
        try writer.print("{s}        ;;\n", .{indent});
    }

    // Default: no (recognised) next subcommand typed yet → offer this node's
    // children as the next completion.
    try writer.print("{s}    *)\n", .{indent});
    try writer.print("{s}        local -a subcommands\n", .{indent});
    try writer.print("{s}        subcommands=(\n", .{indent});
    const entry_indent = try std.mem.concat(arena, u8, &.{ indent, "            " });
    try writeDescribeEntries(arena, writer, entry_indent, node.children);
    try writer.print("{s}        )\n", .{indent});
    try writer.print("{s}        _describe 'subcommand' subcommands\n", .{indent});
    try writer.print("{s}        ;;\n", .{indent});

    try writer.print("{s}esac\n", .{indent});
}

/// Emit the dynamic-completion helper: it invokes `<app> __complete <cword> --
/// <words…>`, reads the NUL-framed `value \t description` records (NUL-delimited
/// so a value may contain spaces/globs/quotes), and offers them via `compadd -d`
/// (display array) with `--` so a value that starts with `-` is not read as an
/// option. Referenced as the action of any positional with a function hook.
fn writeDynamicHelper(writer: anytype, app_name: []const u8) !void {
    try writer.print("_{s}_zcli_complete() {{\n", .{app_name});
    try writer.print("    local cword=$(( _{s}_current - 1 ))\n", .{app_name});
    try writer.writeAll("    local -a __vals __disp\n");
    try writer.writeAll("    local __rec __val __desc __dir=default __first=1\n");
    try writer.writeAll("    while IFS= read -r -d '' __rec; do\n");
    // The first record is the directive; the rest are candidates.
    try writer.writeAll("        if (( __first )); then __dir=$__rec; __first=0; continue; fi\n");
    try writer.writeAll("        __val=${__rec%%$'\\t'*}\n");
    try writer.writeAll("        __vals+=(\"$__val\")\n");
    try writer.writeAll("        if [[ \"$__rec\" == *$'\\t'* ]]; then\n");
    try writer.writeAll("            __desc=${__rec#*$'\\t'}\n");
    try writer.writeAll("            __disp+=(\"${__val}  --  ${__desc}\")\n");
    try writer.writeAll("        else\n");
    try writer.writeAll("            __disp+=(\"$__val\")\n");
    try writer.writeAll("        fi\n");
    try writer.print("    done < <(\"${{_{s}_words[1]}}\" __complete \"$cword\" -- \"${{_{s}_words[@]}}\" 2>/dev/null)\n", .{ app_name, app_name });
    try writer.writeAll("    (( ${#__vals} )) && compadd -d __disp -- \"${__vals[@]}\"\n");
    // Combine directive: also offer native file/dir completion.
    try writer.writeAll("    case $__dir in\n");
    try writer.writeAll("        also_files) _files ;;\n");
    try writer.writeAll("        also_dirs) _files -/ ;;\n");
    try writer.writeAll("    esac\n");
    try writer.writeAll("}\n\n");
}

/// Emit the `_arguments` call for a leaf command: its options plus a spec for
/// each declared positional. Enum positionals offer their choices; every other
/// positional shows its name/description as a hint (an empty action = describe
/// but complete nothing). There is deliberately NO file fallback — a command
/// that takes an id or an enum should not dump the working directory.
fn writeLeafArguments(
    arena: std.mem.Allocator,
    writer: anytype,
    app_name: []const u8,
    indent: []const u8,
    node: *const tree.CommandNode,
) !void {
    var specs = std.ArrayList([]const u8).empty;
    try appendOptionSpecs(arena, &specs, app_name, node.options);
    try appendPositionalSpecs(arena, &specs, app_name, node.args);

    // Nothing declared → nothing to complete for this command.
    if (specs.items.len == 0) return;

    // Namespace the context so option state doesn't leak between commands. The
    // path sits in a double-quoted string, so dq-escape it (a `$(…)`/backtick in
    // a name must not run).
    const ctx = try dquoteEscape(arena, try std.mem.join(arena, "-", node.path));
    try writer.print("{s}        curcontext=\"${{curcontext%:*:*}}:{s}:\"\n", .{ indent, ctx });
    try writer.print("{s}        _arguments -S \\\n", .{indent});
    const spec_indent = try std.mem.concat(arena, u8, &.{ indent, "            " });
    for (specs.items, 0..) |spec, i| {
        const cont = if (i + 1 < specs.items.len) " \\" else "";
        try writer.print("{s}'{s}'{s}\n", .{ spec_indent, spec, cont });
    }
}

/// Emit `_arguments` option specs (one `\`-continued line per form) at `indent`.
/// Used by the top-level `_arguments` where fixed specs always follow, so every
/// line keeps its trailing backslash.
fn writeOptionSpecs(
    arena: std.mem.Allocator,
    writer: anytype,
    app_name: []const u8,
    indent: []const u8,
    options: []const zcli.OptionInfo,
) !void {
    var specs = std.ArrayList([]const u8).empty;
    try appendOptionSpecs(arena, &specs, app_name, options);
    for (specs.items) |spec| try writer.print("{s}'{s}' \\\n", .{ indent, spec });
}

/// Append one `_arguments` spec string (unquoted, unindented) per option form.
fn appendOptionSpecs(
    arena: std.mem.Allocator,
    specs: *std.ArrayList([]const u8),
    app_name: []const u8,
    options: []const zcli.OptionInfo,
) !void {
    for (options) |opt| {
        const esc_desc = if (opt.description) |d| try escape.zsh(arena, d) else null;
        const esc_name = try escape.zsh(arena, opt.name);
        const action = try optionAction(arena, app_name, opt);

        if (opt.short) |short| {
            const esc_short = try escape.zsh(arena, &[_]u8{short});
            const spec = if (esc_desc) |d|
                try std.fmt.allocPrint(arena, "-{s}[{s}]{s}", .{ esc_short, d, action })
            else
                try std.fmt.allocPrint(arena, "-{s}{s}", .{ esc_short, action });
            try specs.append(arena, spec);
        }
        const spec = if (esc_desc) |d|
            try std.fmt.allocPrint(arena, "--{s}[{s}]{s}", .{ esc_name, d, action })
        else
            try std.fmt.allocPrint(arena, "--{s}{s}", .{ esc_name, action });
        try specs.append(arena, spec);
    }
}

/// Append one positional `_arguments` spec per declared arg. `pos` is the 1-based
/// index, or `*` for a variadic arg that soaks up the rest:
///   'N:message:(a b c)'          → an enum arg; offer its choices
///   'N: : _message -r "message"' → any other arg; force-display a hint
///
/// Non-enum positionals use `_message -r` rather than an empty action because an
/// empty action's message only renders when the user has a `format`/`descriptions`
/// zstyle set (most don't) — so it would silently show nothing. `_message -r`
/// displays unconditionally. There is deliberately no `_files` fallback.
fn appendPositionalSpecs(
    arena: std.mem.Allocator,
    specs: *std.ArrayList([]const u8),
    app_name: []const u8,
    args: []const zcli.ArgInfo,
) !void {
    for (args, 1..) |arg, idx| {
        const pos = if (arg.is_variadic)
            try arena.dupe(u8, "*")
        else
            try std.fmt.allocPrint(arena, "{d}", .{idx});

        const msg = arg.description orelse arg.name;

        // A declared `.complete` (function hook or `.file`/`.dir` builtin) takes
        // precedence and sets the `_arguments` action directly.
        const spec = if (arg.complete) |c| blk: {
            const esc_msg = try escape.zsh(arena, msg);
            const action = switch (c) {
                .hook => try std.fmt.allocPrint(arena, "_{s}_zcli_complete", .{app_name}),
                .file => "_files",
                .dir => "_files -/",
            };
            break :blk try std.fmt.allocPrint(arena, "{s}:{s}:{s}", .{ pos, esc_msg, action });
        } else if (arg.enum_values) |values| blk: {
            const esc_msg = try escape.zsh(arena, msg);
            const group = try enumActionGroup(arena, values);
            break :blk try std.fmt.allocPrint(arena, "{s}:{s}:{s}", .{ pos, esc_msg, group });
        } else blk: {
            // Build `pos: : _message -r "<msg>"`, then dance single quotes so the
            // whole token is safe inside the outer '…' the caller wraps it in. The
            // message sits in double quotes (dq-escaped); its single quotes are
            // handled by the dance — two non-overlapping escape layers.
            const raw = try std.fmt.allocPrint(arena, "{s}: : _message -r \"{s}\"", .{ pos, try dquoteEscape(arena, msg) });
            break :blk try danceSingleQuotes(arena, raw);
        };
        try specs.append(arena, spec);
    }
}

/// Escape for placement inside a zsh double-quoted string: backslash-escape the
/// four chars zsh expands there (`\`, `"`, `$`, `` ` ``).
fn dquoteEscape(arena: std.mem.Allocator, s: []const u8) ![]const u8 {
    var out = std.ArrayList(u8).empty;
    for (s) |c| {
        switch (c) {
            '\\', '"', '$', '`' => {
                try out.append(arena, '\\');
                try out.append(arena, c);
            },
            else => try out.append(arena, c),
        }
    }
    return out.items;
}

/// Replace each single quote with the `'\''` sequence so the string is safe to
/// place inside an outer `'…'` (the classic shell single-quote dance).
fn danceSingleQuotes(arena: std.mem.Allocator, s: []const u8) ![]const u8 {
    var out = std.ArrayList(u8).empty;
    for (s) |c| {
        if (c == '\'') try out.appendSlice(arena, "'\\''") else try out.append(arena, c);
    }
    return out.items;
}

/// The zsh `_arguments` action suffix for an option:
///   ""                            → boolean flag
///   ":name:"                      → takes an arbitrary value
///   ":name:(a b c)"               → takes one of the enum values
///   ":name:_<app>_zcli_complete"  → dynamic hook (calls `__complete`)
///   ":name:_files"/":name:_files -/" → the `.file`/`.dir` builtin
fn optionAction(arena: std.mem.Allocator, app_name: []const u8, opt: zcli.OptionInfo) ![]const u8 {
    // The option name is the action's message; it lands inside the single-quoted
    // spec the caller wraps, so escape.zsh it (single-quote dance + spec metachars).
    const esc_name = try escape.zsh(arena, opt.name);
    if (opt.complete) |c| {
        switch (c) {
            .hook => return std.fmt.allocPrint(arena, ":{s}:_{s}_zcli_complete", .{ esc_name, app_name }),
            .file => return std.mem.concat(arena, u8, &.{ ":", esc_name, ":_files" }),
            .dir => return std.mem.concat(arena, u8, &.{ ":", esc_name, ":_files -/" }),
        }
    }
    if (opt.enum_values) |values| {
        const group = try enumActionGroup(arena, values);
        return std.mem.concat(arena, u8, &.{ ":", esc_name, ":", group });
    }
    if (opt.takes_value) {
        return std.mem.concat(arena, u8, &.{ ":", esc_name, ":" });
    }
    return "";
}

/// A parenthesised, space-separated zsh action group of escaped enum values,
/// e.g. `(low medium high)`. The parens are literal zsh spec syntax, so only the
/// individual values are escaped — never the group as a whole.
fn enumActionGroup(arena: std.mem.Allocator, values: []const []const u8) ![]const u8 {
    var out = std.ArrayList(u8).empty;
    try out.append(arena, '(');
    for (values, 0..) |v, idx| {
        if (idx > 0) try out.append(arena, ' ');
        try out.appendSlice(arena, try escape.zsh(arena, v));
    }
    try out.append(arena, ')');
    return out.items;
}

/// Emit `_describe` entries (`'name:desc'`, aliases as separate entries) for a
/// set of sibling command nodes.
fn writeDescribeEntries(
    arena: std.mem.Allocator,
    writer: anytype,
    indent: []const u8,
    nodes: []const *tree.CommandNode,
) !void {
    for (nodes) |child| {
        try writeDescribeEntry(arena, writer, indent, child.name, child.description);
        for (child.aliases) |alias| {
            try writeDescribeEntry(arena, writer, indent, alias, child.description);
        }
    }
}

fn writeDescribeEntry(
    arena: std.mem.Allocator,
    writer: anytype,
    indent: []const u8,
    name: []const u8,
    description: ?[]const u8,
) !void {
    // The name heads a single-quoted `_describe` entry (`'name:desc'`), so
    // escape.zsh it: the single-quote dance plus the `:` separator it splits on.
    try writer.print("{s}'{s}", .{ indent, try escape.zsh(arena, name) });
    if (description) |d| {
        const esc = try escape.zsh(arena, d);
        try writer.print(":{s}", .{esc});
    }
    try writer.writeAll("'\n");
}

/// `unit` repeated `n` times, arena-allocated.
fn repeat(arena: std.mem.Allocator, unit: []const u8, n: usize) ![]const u8 {
    var out = std.ArrayList(u8).empty;
    for (0..n) |_| try out.appendSlice(arena, unit);
    return out.items;
}
