const std = @import("std");
const zcli = @import("zcli");
const tree = @import("tree.zig");
const escape = @import("escape.zig");

/// Generate a zsh completion script for the given app.
///
/// This is the reference generator: its `_arguments`/`_describe`/nested
/// `case $line[N]` output is the behaviour the bash and fish generators mirror.
/// It renders purely over the shared `tree.CommandNode` structure and routes all
/// descriptions/values through `escape.zsh`.
pub fn generate(
    allocator: std.mem.Allocator,
    app_name: []const u8,
    commands: []const zcli.CommandInfo,
    global_options: []const zcli.OptionInfo,
) ![]const u8 {
    var arena_state = std.heap.ArenaAllocator.init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const root = try tree.build(arena, commands);

    var aw: std.Io.Writer.Allocating = .init(allocator);
    errdefer aw.deinit();
    const writer = &aw.writer;

    try writer.print("#compdef {s}\n", .{app_name});
    try writer.print("# zsh completion for {s}\n", .{app_name});
    try writer.writeAll("# Generated by zcli-completions plugin\n\n");

    try writer.print("_{s}() {{\n", .{app_name});
    try writer.writeAll("    local curcontext=\"$curcontext\" line state\n");
    try writer.writeAll("    typeset -A opt_args\n\n");

    // Top-level _arguments: global options + a command slot + the rest.
    try writer.writeAll("    _arguments -S -C \\\n");
    try writeOptionSpecs(arena, writer, "        ", global_options);
    try writer.writeAll("        '1: :->command' \\\n");
    try writer.writeAll("        '*::arg:->args'\n\n");

    try writer.writeAll("    case $state in\n");

    // command state: list root commands.
    try writer.writeAll("        command)\n");
    try writer.writeAll("            local -a commands\n");
    try writer.writeAll("            commands=(\n");
    try writeDescribeEntries(arena, writer, "                ", root.children);
    try writer.writeAll("            )\n");
    try writer.writeAll("            _describe 'command' commands\n");
    try writer.writeAll("            ;;\n");

    // args state: dispatch on the entered subcommand path.
    try writer.writeAll("        args)\n");
    try writeArgsDispatch(arena, writer, root, 1);
    try writer.writeAll("            ;;\n");

    try writer.writeAll("    esac\n");
    try writer.writeAll("}\n\n");

    try writer.print("_{s} \"$@\"\n", .{app_name});

    var al = aw.toArrayList();
    return al.toOwnedSlice(allocator);
}

/// Emit the `case $line[depth] in … esac` block that handles each child of
/// `node`: recurse into groups, or emit option/arg completions for leaves.
fn writeArgsDispatch(
    arena: std.mem.Allocator,
    writer: anytype,
    node: *const tree.CommandNode,
    depth: usize,
) !void {
    const indent = try repeat(arena, "    ", depth + 2);
    try writer.print("{s}case $line[{d}] in\n", .{ indent, depth });

    for (node.children) |child| {
        // Match the child by name or any alias.
        try writer.print("{s}    {s}", .{ indent, child.name });
        for (child.aliases) |alias| try writer.print("|{s}", .{alias});
        try writer.writeAll(")\n");

        if (child.children.len > 0) {
            // Group: recurse to dispatch on the next path element.
            try writeArgsDispatch(arena, writer, child, depth + 1);
        } else {
            // Leaf: complete this command's options and positional args.
            try writeLeafArguments(arena, writer, indent, child);
        }
        try writer.print("{s}        ;;\n", .{indent});
    }

    // Default: no (recognised) next subcommand typed yet → offer this node's
    // children as the next completion.
    try writer.print("{s}    *)\n", .{indent});
    try writer.print("{s}        local -a subcommands\n", .{indent});
    try writer.print("{s}        subcommands=(\n", .{indent});
    const entry_indent = try std.mem.concat(arena, u8, &.{ indent, "            " });
    try writeDescribeEntries(arena, writer, entry_indent, node.children);
    try writer.print("{s}        )\n", .{indent});
    try writer.print("{s}        _describe 'subcommand' subcommands\n", .{indent});
    try writer.print("{s}        ;;\n", .{indent});

    try writer.print("{s}esac\n", .{indent});
}

/// Emit the `_arguments` call for a leaf command (its options + a file fallback
/// for positionals).
fn writeLeafArguments(
    arena: std.mem.Allocator,
    writer: anytype,
    indent: []const u8,
    node: *const tree.CommandNode,
) !void {
    // Namespace the context so option state doesn't leak between commands.
    const ctx = try std.mem.join(arena, "-", node.path);
    try writer.print("{s}        curcontext=\"${{curcontext%:*:*}}:{s}:\"\n", .{ indent, ctx });
    try writer.print("{s}        _arguments -S \\\n", .{indent});
    const spec_indent = try std.mem.concat(arena, u8, &.{ indent, "            " });
    try writeOptionSpecs(arena, writer, spec_indent, node.options);
    // Positional fallback: complete files for any remaining args.
    try writer.print("{s}'*::arg:_files'\n", .{spec_indent});
}

/// Emit `_arguments` option specs (one line per form, `\`-continued) at `indent`.
fn writeOptionSpecs(
    arena: std.mem.Allocator,
    writer: anytype,
    indent: []const u8,
    options: []const zcli.OptionInfo,
) !void {
    for (options) |opt| {
        const esc_desc = if (opt.description) |d| try escape.zsh(arena, d) else null;
        const action = try optionAction(arena, opt);

        if (opt.short) |short| {
            try writer.print("{s}'-{c}", .{ indent, short });
            if (esc_desc) |d| try writer.print("[{s}]", .{d});
            try writer.print("{s}' \\\n", .{action});
        }
        try writer.print("{s}'--{s}", .{ indent, opt.name });
        if (esc_desc) |d| try writer.print("[{s}]", .{d});
        try writer.print("{s}' \\\n", .{action});
    }
}

/// The zsh `_arguments` action suffix for an option:
///   ""                          → boolean flag
///   ":name:"                    → takes an arbitrary value
///   ":name:(a b c)"             → takes one of the enum values
fn optionAction(arena: std.mem.Allocator, opt: zcli.OptionInfo) ![]const u8 {
    if (opt.enum_values) |values| {
        var out = std.ArrayList(u8).empty;
        try out.appendSlice(arena, ":");
        try out.appendSlice(arena, opt.name);
        try out.appendSlice(arena, ":(");
        for (values, 0..) |v, idx| {
            if (idx > 0) try out.append(arena, ' ');
            const esc = try escape.zsh(arena, v);
            try out.appendSlice(arena, esc);
        }
        try out.appendSlice(arena, ")");
        return out.items;
    }
    if (opt.takes_value) {
        return std.mem.concat(arena, u8, &.{ ":", opt.name, ":" });
    }
    return "";
}

/// Emit `_describe` entries (`'name:desc'`, aliases as separate entries) for a
/// set of sibling command nodes.
fn writeDescribeEntries(
    arena: std.mem.Allocator,
    writer: anytype,
    indent: []const u8,
    nodes: []const *tree.CommandNode,
) !void {
    for (nodes) |child| {
        try writeDescribeEntry(arena, writer, indent, child.name, child.description);
        for (child.aliases) |alias| {
            try writeDescribeEntry(arena, writer, indent, alias, child.description);
        }
    }
}

fn writeDescribeEntry(
    arena: std.mem.Allocator,
    writer: anytype,
    indent: []const u8,
    name: []const u8,
    description: ?[]const u8,
) !void {
    try writer.print("{s}'{s}", .{ indent, name });
    if (description) |d| {
        const esc = try escape.zsh(arena, d);
        try writer.print(":{s}", .{esc});
    }
    try writer.writeAll("'\n");
}

/// `unit` repeated `n` times, arena-allocated.
fn repeat(arena: std.mem.Allocator, unit: []const u8, n: usize) ![]const u8 {
    var out = std.ArrayList(u8).empty;
    for (0..n) |_| try out.appendSlice(arena, unit);
    return out.items;
}
