name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux
            zig_target: x86_64-linux-musl
          - os: ubuntu-latest
            target: aarch64-linux
            zig_target: aarch64-linux-musl
          - os: macos-latest
            target: x86_64-macos
            zig_target: x86_64-macos
          - os: macos-latest
            target: aarch64-macos
            zig_target: aarch64-macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Build zcli
        run: |
          cd projects/zcli
          zig build -Doptimize=ReleaseFast -Dtarget=${{ matrix.zig_target }}

      - name: Package binary
        run: |
          cd projects/zcli
          mkdir -p dist
          if [[ "${{ matrix.target }}" == *"macos"* ]]; then
            cp zig-out/bin/zcli dist/zcli-${{ matrix.target }}
          else
            cp zig-out/bin/zcli dist/zcli-${{ matrix.target }}
          fi
          chmod +x dist/zcli-${{ matrix.target }}

      - name: Generate checksum
        run: |
          cd projects/zcli/dist
          shasum -a 256 zcli-${{ matrix.target }} > zcli-${{ matrix.target }}.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zcli-${{ matrix.target }}
          path: |
            projects/zcli/dist/zcli-${{ matrix.target }}
            projects/zcli/dist/zcli-${{ matrix.target }}.sha256

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Flatten artifact structure
        run: |
          mkdir -p release
          find dist -type f -name 'zcli-*' -exec cp {} release/ \;
          ls -la release/

      - name: Create checksums file
        run: |
          cd release
          cat *.sha256 > checksums.txt
          rm *.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
